// Add missing abbreviations to words with empty abbr field
const fs = require('fs');

// Mapping: en term → abbreviation to add
// Only universally recognized, standard medical abbreviations
const abbrMap = {
  // === 疾患・症候群 ===
  "Angina pectoris": "AP",
  "Hepatic encephalopathy": "HE",
  "Esophageal varices": "EV",
  "Kawasaki disease": "KD",
  "Bipolar disorder": "BD",
  "Nephrotic syndrome": "NS",
  "Nephritic syndrome": "NephS",
  "Ectopic pregnancy": "EP",
  "Preterm labor": "PTL",
  "Down syndrome": "DS",
  "Pyloric stenosis": "PS",
  "Hearing loss": "HL",
  "Paraneoplastic syndrome": "PNS",
  "Lung cancer": "LC",
  "Breast cancer": "BC",
  "Gastric cancer": "GC",
  "Thyroid cancer": "TC",
  "Cervical cancer": "CxCa",
  "Ovarian cancer": "OvCa",
  "Bladder cancer": "BCa",
  "Compartment syndrome": "CS",
  "Febrile seizure": "FS",
  "Graves' disease": "GD",
  "Hashimoto thyroiditis": "HT",
  "Addison's disease": "AD",
  "Cushing's syndrome": "CS",
  "Thyroid storm": "TS",
  "Acromegaly": "Acro",
  "Hemochromatosis": "HH",
  "Wilson's disease": "WD",
  "Hydrocephalus": "HC",
  "Meningioma": "MNG",
  "Brain tumor": "BT",
  "Celiac disease": "CeD",
  "Bronchiectasis": "BE",
  "Kidney transplant": "KTx",
  "Reactive arthritis": "ReA",
  "Septic shock": "SS",
  "Portal hypertension": "PHT",
  "Liver cirrhosis": "LC",
  "Aortic dissection": "AD",
  "Pyelonephritis": "pyelo",
  "Hydronephrosis": "HN",
  "Endometriosis": "EM",
  "Uterine fibroids": "UF",
  "Schizophrenia": "SZ",
  "Panic disorder": "PD",
  "Eating disorder": "ED",
  "Meniere's disease": "MD",
  "Cholesteatoma": "Chol",
  "Osteomyelitis": "OM",
  "Osteosarcoma": "OS",
  "Intussusception": "IS",
  "Epiglottitis": "Epi",
  "Bronchiolitis": "Bronch",
  "Aspergillosis": "Asp",
  "Candidiasis": "Cand",
  "Cryptococcosis": "Crypto",
  "Dengue fever": "DF",
  "Typhoid fever": "TF",
  "Lyme disease": "LD",
  "Syphilis": "Syph",
  "Malaria": "Mal",
  "Constrictive pericarditis": "CP",
  "Rhabdomyolysis nephropathy": "Rhabdo",
  "Refeeding syndrome": "RFS",
  "Splenomegaly": "SM",
  "Hepatomegaly": "HM",
  "Pericardial effusion": "PE",
  "Constipation": "const",

  // === 解剖・構造 ===
  "Intervertebral disc": "IVD",
  "Common peroneal nerve": "CPN",
  "Spinal cord": "SC",
  "Brachial plexus": "BP",
  "Cauda equina": "CE",
  "Inferior vena cava": "IVC",
  "Bundle of His": "His",
  "Purkinje fibers": "PF",
  "Ascending aorta": "AAo",
  "Descending aorta": "DAo",
  "Aortic arch": "AA",

  // === 検査・処置 ===
  "Spinal anesthesia": "SA",
  "Regional anesthesia": "RA",
  "Epidural anesthesia": "EA",
  "Colonoscopy": "CS",
  "Spirometry": "Spiro",
  "Bone scan": "BS",
  "Doppler ultrasound": "DUS",
  "Mammography": "MMG",
  "Angiography": "Angio",
  "Fluoroscopy": "Fluoro",
  "Fundoscopy": "Fundus",
  "Audiometry": "Audio",
  "Tympanometry": "Tympa",
  "Cystoscopy": "Cysto",
  "Bronchoscopy": "Broncho",
  "Laparoscopy": "Lap",
  "Laparotomy": "LT",
  "Thoracentesis": "Thora",
  "Paracentesis": "Para",
  "Pericardiocentesis": "Pericardio",
  "Amniocentesis": "Amnio",
  "Arthroscopy": "Arthro",
  "Uroflowmetry": "UFM",
  "Electrocardiogram": "ECG",

  // === 手術 ===
  "Appendectomy": "Appy",
  "Cholecystectomy": "CCY",
  "Colostomy": "Colo",
  "Mastectomy": "Mx",
  "Thyroidectomy": "TDY",
  "Hysterectomy": "TAH",
  "Nephrectomy": "Nx",
  "Prostatectomy": "Px",
  "Splenectomy": "SpX",
  "Gastrectomy": "Gx",
  "Hemicolectomy": "HC",
  "Craniotomy": "Crani",
  "Laminectomy": "Lami",
  "Discectomy": "Disco",
  "Fasciotomy": "Fascio",
  "Whipple procedure": "PD",
  "Cardioversion": "DCCV",
  "Ablation": "Abl",
  "Pleurodesis": "Pleuro",
  "Embolization": "Embo",
  "Cricothyrotomy": "Cric",
  "Escharotomy": "Eschar",

  // === 薬剤 ===
  "Oxytocin": "OT",
  "Metformin": "Met",
  "Glucagon": "GCG",
  "Colchicine": "Col",
  "Allopurinol": "Allo",
  "Isotretinoin": "ISO",
  "Dantrolene": "Dant",
  "Oseltamivir": "Osel",
  "Furosemide": "Furo",
  "Lactulose": "Lact",
  "Ketamine": "Ket",
  "Digoxin": "Dig",
  "Atropine": "Atrop",
  "Morphine": "MS",
  "Fentanyl": "Fent",

  // === 症状・所見 ===
  "Dysphagia": "Dys",
  "Tachypnea": "TP",
  "Bradypnea": "BP",
  "Breathlessness": "SOB",
  "Stridor": "Strid",
  "Hemoptysis": "Hemo",
  "Hematemesis": "HM",
  "Hematuria": "HU",
  "Melena": "Mel",
  "Hematochezia": "HCZ",
  "Proteinuria": "PU",
  "Polyuria": "PU",
  "Nocturia": "Noct",
  "Dysuria": "DU",
  "Epistaxis": "Epi",
  "Jaundice": "Ict",
  "Ascites": "Asc",
  "Papilledema": "Pap",
  "Nystagmus": "Nyst",
  "Tinnitus": "Tin",
  "Vertigo": "Vert",
  "Diplopia": "Dipl",

  // === 分類・スコア ===
  "Apgar score": "APGAR",
  "Braden scale": "Braden",
  "Wells score": "Wells",
  "Mallampati score": "Mallampati",

  // === その他の一般用語 ===
  "Blood transfusion": "BT",
  "Palliative care": "PC",
  "Smoking cessation": "SC",
  "Anticoagulation": "AC",
  "Anticoagulant": "AC",
  "Defibrillation": "Defib",
  "Resuscitation": "Resus",
  "Vaccination": "Vx",
  "Immunotherapy": "IT",
  "Targeted therapy": "TT",
  "Hormone therapy": "HT",
  "Palliative chemotherapy": "pChemo",
  "Phototherapy": "PT",
  "Nutritional assessment": "NA",
  "Infection control precautions": "ICP",

  // === 後半バッチの単語（2874行以降） ===
  "Cushing syndrome": "CS",
  "Cushing disease": "CD",
  "Behcet disease": "BD",
  "Behçet disease": "BD",
  "Dressler syndrome": "DS",
  "DiGeorge syndrome": "DGS",
  "Ehlers-Danlos syndrome": "EDS",
  "Crigler-Najjar syndrome": "CNS",
  "Cronkhite-Canada syndrome": "CCS",
  "Boerhaave syndrome": "BS",
  "Fitz-Hugh-Curtis syndrome": "FHCS",
  "Horner syndrome": "HS",
  "Hirschsprung disease": "HD",
  "Brown-Sequard syndrome": "BSS",
  "Friedreich ataxia": "FA",
  "Goodpasture syndrome": "GPS",
  "Gaucher disease": "GD",
  "Gilbert syndrome": "GS",
  "Gilles de la Tourette syndrome": "GTS",
  "Plummer-Vinson syndrome": "PVS",
  "Chagas disease": "ChD",
  "Broca aphasia": "BA",
  "Klinefelter syndrome": "KS",
  "Korsakoff syndrome": "KS",
  "Lennox-Gastaut syndrome": "LGS",
  "Laurence-Moon-Biedl syndrome": "LMBS",
  "Laron syndrome": "LS",
  "Lance-Adams syndrome": "LAS",
  "Kennedy disease": "KD",
  "Kartagener syndrome": "KS",
  "Kasabach-Merritt syndrome": "KMS",
  "Kallmann syndrome": "KS",
  "Klüver-Bucy syndrome": "KBS",
  "Le Fort fracture": "LF",
  "Legionella pneumonia": "LP",

  // === 臨床所見・徴候 ===
  "Cardiogenic shock": "CS",
  "Hemorrhagic shock": "HS",
  "Hypovolemic shock": "HVS",
  "Distributive shock": "DS",
  "Obstructive shock": "OS",
  "Cardiac tamponade": "CT",
  "Tension pneumothorax": "TPTX",
  "Hemothorax": "HTX",
  "Flail chest": "FC",
  "Chylothorax": "ChT",
  "Cardiomegaly": "CM",
  "Pancytopenia": "PCP",
  "Agranulocytosis": "AGR",
  "Neutropenia": "NP",
  "Erythrocytosis": "EC",
  "Hemolytic anemia": "HA",
  "Coagulopathy": "Coag",
  "Hypercoagulable state": "HCS",
  "Fulminant hepatitis": "FH",

  // === 医療行為・管理 ===
  "Ventilator weaning": "VW",
  "Prone positioning": "PP",
  "Nutritional screening": "NS",
  "Early mobilization": "EM",
  "Discharge planning": "DP",
  "Code blue": "CB",
  "Organ donation": "OD",
  "Brain death": "BD",
  "Autopsy": "PME",

  // === 皮膚所見 ===
  "Erythema": "ER",
  "Purpura": "Purp",
  "Petechiae": "Pet",
  "Urticaria": "Urt",
  "Cellulitis": "Cell",
  "Impetigo": "Imp",
  "Dermatitis": "Derm",
  "Psoriasis": "Pso",
  "Melanoma": "MM",
  "Rosacea": "Ros",
  "Vitiligo": "Vit",
  "Keloid": "Kel",
  "Scabies": "Scab",

  // === 解剖学 骨 ===
  "Mandible": "Mand",
  "Clavicle": "Clav",
  "Scapula": "Scap",
  "Pelvis": "Pelv",
  "Calcaneus": "Calc",
  "Talus": "Tal",
  "Coccyx": "Cx",
  "Sacrum": "S",
  "Femur": "Fem",
  "Tibia": "Tib",
  "Fibula": "Fib",
  "Humerus": "Hum",
  "Radius": "Rad",
  "Ulna": "Uln",
  "Patella": "Pat",
};

const content = fs.readFileSync('words.js', 'utf8');
const lines = content.split('\n');
let count = 0;
let applied = [];

for (let i = 0; i < lines.length; i++) {
  const line = lines[i];
  // Only process lines with abbr:""
  if (!line.includes('abbr:""')) continue;

  // Extract the en field value
  const enMatch = line.match(/en:"([^"]+)"/);
  if (!enMatch) continue;
  const en = enMatch[1];

  if (abbrMap[en]) {
    const abbr = abbrMap[en];
    lines[i] = line.replace('abbr:""', `abbr:"${abbr}"`);
    count++;
    applied.push(`${en} → ${abbr}`);
  }
}

fs.writeFileSync('words.js', lines.join('\n'));
console.log(`${count}件の略語を追加`);
applied.forEach(a => console.log('  ' + a));
