/**
 * 英語見出し（en）→ 例文の日本語訳（exampleJa）
 * 未登録の語は空のまま。随時ここに追記して node migrate-example-ja.js && node build.js
 */
module.exports = {
  'Chief complaint': '本日の主訴は何ですか。',
  'Medical history': '患者に重要な既往歴はありますか。',
  Allergies: '既知の薬物アレルギーはありますか。',
  'Informed consent': '処置前にインフォームドコンセントを得た。',
  'Where does it hurt?': 'どこが痛いですか。その部位を指してください。',
  'When did it start?': '痛みはいつからですか。突然でしたか、それとも徐々に始まりましたか。',
  'How long has this been going on?': 'この症状はどのくらい続いていますか。',
  'On a scale of 0 to 10': '痛みを0から10のスケールで表すと、何点ですか。',
  'Does it radiate?': '痛みは腕や顎に放散しますか。',
  'What makes it better or worse?': '何をすると痛みが楽になりますか、悪化しますか。',
  'Have you had this before?': '以前にも同様の痛みを経験したことはありますか。',
  'Do you take any medications?': '市販薬を含め、何かお薬を飲んでいますか。',
  'Do you smoke?': '喫煙はされますか。される場合、1日何箱ですか。',
  'Do you drink alcohol?': 'お酒はどのくらいの頻度・量を飲まれますか。',
  'Family history': '心疾患や糖尿病の家族歴はありますか。',
  'Social history': '社会歴について伺います。お仕事は何をされていますか。',
  'Review of systems': '系統的問診を行い、ほかの症状がないか確認します。',
  "I'm going to examine you now.": 'これから診察します。不快なことがあれば教えてください。',
  'Please take a deep breath.': '深呼吸をしてください。吸って、吐いてください。',
  'Does this hurt?': 'ここを押すと痛みますか。',
  'Please point to where the pain is.': '痛みのある場所を正確に指し示してください。',
  "I'd like to run some tests.": '症状の原因を調べるために、いくつか検査をしたいと思います。',
  "We'll need to admit you to the hospital.": '精査のため入院が必要です。',
  'You can be discharged today.': '検査結果は良好です。本日退院できます。',
  'Please follow up in one week.': '1週間後に主治医の外来を受診してください。',
  Onset: '症状の発症は突然でしたか、それとも徐々にでしたか。',
  Duration: '1回あたりの症状の持続時間はどのくらいですか。',
  Severity: '痛みの強さをどのように評価しますか。',
  'Associated symptoms': '発熱や悪寒などの随伴症状はありますか。',
  Acute: '患者は急性腹痛で受診した。',
  Chronic: '彼女は過去2年間、慢性的な腰痛がある。',
  Bilateral: '患者は両膝に痛みがある。',
  Unilateral: '片側の下肢腫脹を訴えている。',
  Proximal: '両下肢に近位筋力低下がある。',
  Distal: '遠位の脈拍は両側とも触知できる。',
  Anterior: '触診で膝前面に痛みがある。',
  Posterior: '後脛骨動脈は触知できた。',
  Medial: '内側関節線に圧痛を認めた。',
  Lateral: '外側足関節捻挫と診断した。',
  Superior: '上盂唇断裂を認めた。',
  Inferior: '肺の下縁は打診で濁音だった。',
  Benign: '生検で良性腫瘍が確認された。',
  Malignant: '生検で悪性細胞が見つかった。',
  Idiopathic: '特発性肺線維症と診断された。',
  Contraindication: '消化性潰瘍の患者にはアスピリンは禁忌である。',
  Indication: 'この患者に手術の適応は何ですか。',
  Prognosis: '早期がんの予後は一般に良好である。',
  'Differential diagnosis': '鑑別診断には虫垂炎と卵巣嚢腫が含まれる。',
  'Working diagnosis': '培養結果待ちの暫定診断は肺炎である。',
  Stat: 'この患者に至急心電図を指示してください。',
  Disposition: 'この患者の帰宅・入院などの方針はどうしますか。',
  'Vital signs': '4時間ごとにバイタルサインを確認してください。',
  'Blood pressure': '血圧は140/90 mmHgで、高値である。',
  'Heart rate': '心拍数は不整で110 bpmである。',
  'Respiratory rate': '呼吸数は24回/分で、頻呼吸を示す。',
  'Oxygen saturation': '室内気でSpO2が88%まで低下した。',
  Temperature: '体温は38.9°Cで、発熱がある。',
  'Glasgow Coma Scale': '到着時のGCSは8点で、挿管が検討された。',
  'Mean arterial pressure': '昇圧薬で平均動脈圧は65 mmHg以上に維持されている。',
  'Pulse pressure': '脈圧は70 mmHgと広い。',
  'Capillary refill time': '毛細血管再充満時間は4秒と延長している。',
  Auscultation: '聴診で左側の呼吸音が減弱していた。',
  Palpation: '腹部触診で圧痛のある腫瘤を触知した。',
  Percussion: '打診で右肺底に濁音を認めた。',
  Inspection: '視診で腹部膨隆を認めた。',
  Murmur: '胸骨左縁で収縮期雑音3/6度を聴取した。',
  Rales: '両肺底に細いラ音を聴取した。',
  Wheezing: '両肺野に呼気時喘鳴を聴取した。',
  'Bowel sounds': '四象限いずれでも腸蠕動音は減弱している。',
  Jaundice: '患者は強膜黄染を伴う黄疸を呈している。',
  Cyanosis: '指先に末梢性チアノーゼを認めた。',
  Pallor: '患者は蒼白で、発汗を伴っていた。',
  Diaphoresis: '患者は蒼白で発汗があり、急性冠症候群が疑われた。',
  Edema: '膝まで陥没性浮腫が両側に認められた。',
  Clubbing: 'ばち指を認め、慢性低酸素血症に一致する。',
  Triage: '到着時にトリアージは最優先（immediate）とされた。',
  'Airway, Breathing, Circulation':
    '一次評価：気道は確保、呼吸は十分、循環は安定している。',
  Resuscitation: '到着直後に蘇生を開始した。',
  'Cardiopulmonary resuscitation': '無反応になった直後に心肺蘇生を開始した。',
  Defibrillation: '200ジュールで除細動を行った。',
  Shock: '患者は低血圧性ショックである。輸液蘇生を開始してください。',
  Hypotension: '輸液蘇生にもかかわらず低血圧が持続した。',
  Syncope: '患者は起立時に失神した。',
  'Altered mental status': '患者は fever と意識変容で受診した。',
  'Loss of consciousness': '患者は30秒間の短い意識消失があった。',
  Trauma: '患者は胸部鈍的外傷後に搬送された。',
  'Mechanism of injury': '受傷機転は何でしたか。',
  Sepsis: '患者は敗血症の基準を満たした。',
  Anaphylaxis: '蜂刺症後にアナフィラキシーを発症した。',
  Intubation: '気道保護のため気管内挿管を行った。',
  'Rapid sequence intubation': 'エトミデートとサクシニルコリンでRSIを実施した。',
  'IV access': '太い静脈路を2本確保した。',
  'Fluid resuscitation': '生理食塩液1Lで輸液蘇生を開始した。',
  'Blood culture': '抗菌薬開始前に血液培養を採取した。',
  Laceration: '前額部5cmの裂傷を縫合した。',
  Suture: '創は4-0ナイロンで縫合した。',
  Burn: '上肢と胸部に20%の全身表面積熱傷がある。',
  'Poison / Overdose': 'アセトアミノフェン過量服薬の疑いで搬送された。',
  'Activated charcoal': '経口中毒に対して活性炭を投与した。',
  'Point-of-care ultrasound': 'POCUSで腹腔内に遊離液体を認めた。',
  'FAST exam': 'FASTでモリソン窩に遊離液体を認めた。',
  'Do not resuscitate': '患者にはDNR指示が記録されている。',
  Fever: '子どもは2日間39°Cの発熱がある。',
  Chills: '患者は悪寒と高熱を訴えている。',
  'Night sweats': '寝汗と意図しない体重減少を訴えている。',
  'Weight loss': '彼は意図せず過去3ヶ月で5kg減量した。',
  Fatigue: '彼女は過去1ヶ月、強い倦怠感を訴えている。',
  Anorexia: '患者は食欲不振で、2日間食事を摂っていない。',
  'Diabetes mellitus': '糖尿病の既往は10年である。',
  Hyperglycemia: '患者は高血糖と意識変容で受診した。',
  Hypoglycemia: '低血糖エピソードがあり、血糖値は45 mg/dLだった。',
  Hypothyroidism: 'TSH 15 mIU/Lと上昇しており、甲状腺機能低下症に一致する。',
  Hyperthyroidism: '患者は触知できる甲状腺腫を伴う甲状腺機能亢進症である。',
  Anemia: '全血球計算でヘモグロビン8.5 g/dLの貧血を認めた。',
  Thrombocytopenia: '血小板数50,000で血小板減少症を認めた。',
  Leukocytosis: '核左方移動を伴う白血球増多は細菌感染を示唆する。',
  'Urinary tract infection': '尿検査で尿路感染症が確認された。',
  'Kidney stones': 'CTで右尿管に6mmの腎結石を認めた。',
  'Acute kidney injury': 'クレアチニン上昇を伴う急性腎障害を発症した。',
  'Chronic kidney disease': '彼女はeGFR 45のCKD3期である。',
  'Liver function tests': '肝機能検査でトランスアミナーゼ上昇、AST 180、ALT 220。',
  Cirrhosis: '患者は腹水を伴うアルコール性肝硬変である。',
  Ascites: '超音波で大量腹水を認めた。',
  CBC: '核左方移動を伴う白血球増多を認めた。',
  BMP: '低ナトリウム血症とクレアチニン上昇を認めた。',
  HbA1c: 'HbA1cは9.2%で、血糖コントロール不良を示す。',
  NPO: '手術前日深夜から絶食としてください。',
  PRN: 'アセトアミノフェン500mg 疼痛時必要時。',
  Discharge: '患者は明日退院可能な状態である。',
};
