const WORDS_DB = [
// ==================== 共通 GEN ====================
{ en:"Chief complaint", abbr:"CC", ja:"主訴", note:"患者が最も困っている症状。問診の最初に確認する。", example:"What is your chief complaint today?", cat:"common", level:"basic", dept:"GEN" },
{ en:"Medical history", abbr:"PMH", ja:"病歴", note:"Past medical history。既往症・手術歴・入院歴を含む。", example:"Does the patient have any significant past medical history?", cat:"common", level:"basic", dept:"GEN" },
{ en:"Allergies", abbr:"NKDA", ja:"アレルギー", note:"NKDA = No Known Drug Allergies。薬剤アレルギーなし。", example:"Does the patient have any known drug allergies?", cat:"common", level:"basic", dept:"GEN" },
{ en:"Informed consent", abbr:"IC", ja:"インフォームドコンセント", note:"処置・手術前に必須。文書で取得する。", example:"Informed consent was obtained before the procedure.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Where does it hurt?", abbr:"", ja:"どこが痛みますか？", note:"痛みの部位確認。Point to where it hurts. とも。", example:"Where does it hurt? Can you point to the area?", cat:"common", level:"basic", dept:"GEN" },
{ en:"When did it start?", abbr:"", ja:"いつから始まりましたか？", note:"発症時期の確認。Onsetの問診。", example:"When did the pain start? Was it sudden or gradual?", cat:"common", level:"basic", dept:"GEN" },
{ en:"How long has this been going on?", abbr:"", ja:"どのくらい続いていますか？", note:"Duration（持続時間）の問診。", example:"How long have you been having these symptoms?", cat:"common", level:"basic", dept:"GEN" },
{ en:"On a scale of 0 to 10", abbr:"", ja:"0から10のスケールで", note:"疼痛スケールの標準表現。0=痛みなし、10=最大の痛み。", example:"On a scale of 0 to 10, how would you rate your pain?", cat:"common", level:"basic", dept:"GEN" },
{ en:"Does it radiate?", abbr:"", ja:"放散しますか？", note:"痛みが他の部位に広がるか確認。Radiationの問診。", example:"Does the pain radiate to your arm or jaw?", cat:"common", level:"basic", dept:"GEN" },
{ en:"What makes it better or worse?", abbr:"", ja:"何をすると楽になる・悪化しますか？", note:"Aggravating / Relieving factorsの問診。", example:"What makes the pain better or worse?", cat:"common", level:"basic", dept:"GEN" },
{ en:"Have you had this before?", abbr:"", ja:"以前にも同じ症状がありましたか？", note:"再発・既往の確認。", example:"Have you experienced this kind of pain before?", cat:"common", level:"basic", dept:"GEN" },
{ en:"Do you take any medications?", abbr:"", ja:"薬は飲んでいますか？", note:"内服薬・市販薬・サプリメントも含めて確認。", example:"Do you take any medications, including over-the-counter drugs?", cat:"common", level:"basic", dept:"GEN" },
{ en:"Do you smoke?", abbr:"", ja:"喫煙しますか？", note:"Pack-year（箱×年数）で喫煙量を表現。", example:"Do you smoke? If so, how many packs per day?", cat:"common", level:"basic", dept:"GEN" },
{ en:"Do you drink alcohol?", abbr:"", ja:"飲酒はしますか？", note:"頻度・量を確認。Drinks per week で表現。", example:"How much alcohol do you drink per week?", cat:"common", level:"basic", dept:"GEN" },
{ en:"Family history", abbr:"FH", ja:"家族歴", note:"遺伝性疾患・生活習慣病のリスク評価に重要。", example:"Is there a family history of heart disease or diabetes?", cat:"common", level:"basic", dept:"GEN" },
{ en:"Social history", abbr:"SH", ja:"社会歴", note:"職業・居住状況・家族構成・ストレスなど。", example:"Let me ask about your social history — where do you work?", cat:"common", level:"basic", dept:"GEN" },
{ en:"Review of systems", abbr:"ROS", ja:"系統的問診", note:"各臓器系統について症状を網羅的に確認する。", example:"I'll now do a review of systems to check for other symptoms.", cat:"common", level:"intermediate", dept:"GEN" },
{ en:"I'm going to examine you now.", abbr:"", ja:"これから診察します。", note:"診察前の一言。患者の不安を和らげる。", example:"I'm going to examine you now. Please let me know if anything is uncomfortable.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Please take a deep breath.", abbr:"", ja:"深呼吸してください。", note:"胸部聴診時の指示。", example:"Please take a deep breath in and out.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Does this hurt?", abbr:"", ja:"ここを押すと痛みますか？", note:"触診・圧迫時の確認。", example:"Does this hurt when I press here?", cat:"common", level:"basic", dept:"GEN" },
{ en:"Please point to where the pain is.", abbr:"", ja:"痛い場所を指してください。", note:"部位特定の指示。", example:"Can you please point to exactly where the pain is?", cat:"common", level:"basic", dept:"GEN" },
{ en:"I'd like to run some tests.", abbr:"", ja:"いくつか検査をしたいと思います。", note:"検査説明の導入文。", example:"I'd like to run some tests to find out what's causing your symptoms.", cat:"common", level:"basic", dept:"GEN" },
{ en:"We'll need to admit you to the hospital.", abbr:"", ja:"入院が必要です。", note:"入院の説明。Admission（入院）に関連。", example:"We'll need to admit you to the hospital for further evaluation.", cat:"common", level:"basic", dept:"GEN" },
{ en:"You can be discharged today.", abbr:"", ja:"本日退院できます。", note:"退院の説明。Discharge instructionsを合わせて説明。", example:"Your results look good — you can be discharged today.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Please follow up in one week.", abbr:"", ja:"1週間後に受診してください。", note:"外来フォローアップの指示。", example:"Please follow up with your doctor in one week.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Onset", abbr:"", ja:"発症", note:"OPQRST（発症・誘因・性状・放散・重症度・時間）の「O」。", example:"What was the onset of your symptoms — sudden or gradual?", cat:"common", level:"basic", dept:"GEN" },
{ en:"Duration", abbr:"", ja:"持続時間", note:"症状がどのくらい続いているか。OPQRST の「T」。", example:"What is the duration of each episode?", cat:"common", level:"basic", dept:"GEN" },
{ en:"Severity", abbr:"", ja:"重症度", note:"OPQRST の「S」。NRS 0–10 で表現。", example:"How would you rate the severity of your pain?", cat:"common", level:"basic", dept:"GEN" },
{ en:"Associated symptoms", abbr:"", ja:"随伴症状", note:"主訴に伴う他の症状。鑑別診断に重要。", example:"Are there any associated symptoms such as fever or chills?", cat:"common", level:"basic", dept:"GEN" },
{ en:"Acute", abbr:"", ja:"急性の", note:"突然発症・短期間。Chronic（慢性）の対語。", example:"The patient presented with acute abdominal pain.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Chronic", abbr:"", ja:"慢性の", note:"長期間続く状態。3ヶ月以上が目安。", example:"She has chronic lower back pain for the past two years.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Bilateral", abbr:"", ja:"両側性の", note:"左右両方。Unilateral（片側）の対語。", example:"The patient has bilateral knee pain.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Unilateral", abbr:"", ja:"片側性の", note:"左右どちらか一方。", example:"She reports unilateral leg swelling.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Proximal", abbr:"", ja:"近位の", note:"体の中心に近い側。Distal（遠位）の対語。", example:"There is proximal muscle weakness in both legs.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Distal", abbr:"", ja:"遠位の", note:"体の中心から遠い側（手先・足先方向）。", example:"Distal pulses are intact bilaterally.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Anterior", abbr:"", ja:"前方の", note:"体の前側。Posterior（後方）の対語。", example:"There is anterior knee pain on palpation.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Posterior", abbr:"", ja:"後方の", note:"体の後ろ側。", example:"Posterior tibial pulse was palpable.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Medial", abbr:"", ja:"内側の", note:"体の中心線に近い側。Lateral（外側）の対語。", example:"Medial joint line tenderness was noted.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Lateral", abbr:"", ja:"外側の", note:"体の中心線から遠い側。", example:"Lateral ankle sprain was confirmed.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Superior", abbr:"", ja:"上方の", note:"頭側。Inferior（下方）の対語。", example:"The superior labrum was torn.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Inferior", abbr:"", ja:"下方の", note:"足側。", example:"The inferior border of the lung was dull to percussion.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Benign", abbr:"", ja:"良性の", note:"悪性（Malignant）でない。腫瘍・疾患の性質表現。", example:"The biopsy confirmed a benign tumor.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Malignant", abbr:"", ja:"悪性の", note:"がん性・生命を脅かす性質。", example:"Malignant cells were found in the biopsy.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Idiopathic", abbr:"", ja:"特発性の", note:"原因不明の疾患に使う。", example:"She was diagnosed with idiopathic pulmonary fibrosis.", cat:"common", level:"intermediate", dept:"GEN" },
{ en:"Contraindication", abbr:"CI", ja:"禁忌", note:"特定の治療・薬剤を使ってはいけない理由。", example:"Aspirin is contraindicated in patients with peptic ulcer.", cat:"common", level:"intermediate", dept:"GEN" },
{ en:"Indication", abbr:"", ja:"適応", note:"治療・処置を行う根拠・理由。", example:"What are the indications for surgery in this patient?", cat:"common", level:"intermediate", dept:"GEN" },
{ en:"Prognosis", abbr:"", ja:"予後", note:"疾患の将来的な経過・見通し。", example:"The prognosis for early-stage cancer is generally good.", cat:"common", level:"intermediate", dept:"GEN" },
{ en:"Differential diagnosis", abbr:"DDx", ja:"鑑別診断", note:"類似症状を呈する疾患を列挙し除外していく過程。", example:"The differential diagnosis includes appendicitis and ovarian cyst.", cat:"common", level:"intermediate", dept:"GEN" },
{ en:"Working diagnosis", abbr:"", ja:"暫定診断", note:"確定前の仮の診断。", example:"Our working diagnosis is pneumonia pending culture results.", cat:"common", level:"intermediate", dept:"GEN" },
{ en:"Stat", abbr:"STAT", ja:"至急", note:"ラテン語 statim。即座に実施する指示。", example:"Order a STAT ECG for this patient.", cat:"common", level:"basic", dept:"GEN" },
{ en:"Disposition", abbr:"", ja:"方針（帰宅・入院）", note:"患者の最終的な行き先。Admit / Discharge / Transfer。", example:"What is the disposition plan for this patient?", cat:"common", level:"intermediate", dept:"GEN" },

// ==================== バイタル GEN ====================
{ en:"Vital signs", abbr:"VS", ja:"バイタルサイン", note:"BP・HR・RR・Temp・SpO2の総称。", example:"Please check the vital signs every 4 hours.", cat:"vital", level:"basic", dept:"GEN" },
{ en:"Blood pressure", abbr:"BP", ja:"血圧", note:"単位はmmHg。収縮期/拡張期で表記。", example:"The BP is 140/90 mmHg, which is elevated.", cat:"vital", level:"basic", dept:"GEN" },
{ en:"Heart rate", abbr:"HR", ja:"心拍数", note:"単位はbpm。Bradycardia(<60) / Tachycardia(>100)。", example:"The heart rate is irregular at 110 bpm.", cat:"vital", level:"basic", dept:"GEN" },
{ en:"Respiratory rate", abbr:"RR", ja:"呼吸数", note:"正常：12–20回/分。Tachypnea >20。", example:"RR is 24, indicating tachypnea.", cat:"vital", level:"basic", dept:"GEN" },
{ en:"Oxygen saturation", abbr:"SpO2", ja:"酸素飽和度", note:"正常：96–100%。90%以下は低酸素血症。", example:"SpO2 dropped to 88% on room air.", cat:"vital", level:"basic", dept:"GEN" },
{ en:"Temperature", abbr:"Temp", ja:"体温", note:"Febrile = 発熱あり(>38.3°C)。Afebrile = 熱なし。", example:"Temperature is 38.9°C — the patient is febrile.", cat:"vital", level:"basic", dept:"GEN" },
{ en:"Glasgow Coma Scale", abbr:"GCS", ja:"グラスゴー・コーマ・スケール", note:"意識レベル評価。目・言語・運動の3項目、最大15点。", example:"GCS is 14 (E4V4M6) on arrival.", cat:"vital", level:"intermediate", dept:"GEN" },
{ en:"Mean arterial pressure", abbr:"MAP", ja:"平均動脈圧", note:"灌流圧の指標。65mmHg以上を目標とすることが多い。", example:"MAP is maintained above 65 mmHg with vasopressors.", cat:"vital", level:"intermediate", dept:"GEN" },
{ en:"Pulse pressure", abbr:"PP", ja:"脈圧", note:"収縮期BP−拡張期BP。Wide / Narrowで評価。", example:"The pulse pressure is wide at 70 mmHg.", cat:"vital", level:"intermediate", dept:"GEN" },
{ en:"Capillary refill time", abbr:"CRT", ja:"毛細血管再充満時間", note:"正常は2秒以内。末梢循環の評価に使う。", example:"Capillary refill time is prolonged at 4 seconds.", cat:"vital", level:"basic", dept:"GEN" },

// ==================== 身体診察 GEN ====================
{ en:"Auscultation", abbr:"", ja:"聴診", note:"心音・呼吸音・腸蠕動音などを聴く。", example:"Auscultation revealed decreased breath sounds on the left.", cat:"diagnosis", level:"basic", dept:"GEN" },
{ en:"Palpation", abbr:"", ja:"触診", note:"圧痛・腫瘤・臓器腫大などを触れて確認する。", example:"Palpation of the abdomen revealed a tender mass.", cat:"diagnosis", level:"basic", dept:"GEN" },
{ en:"Percussion", abbr:"", ja:"打診", note:"Dull（濁音）/ Resonant（共鳴音）/ Tympanic（鼓音）。", example:"Percussion revealed dullness at the right lung base.", cat:"diagnosis", level:"basic", dept:"GEN" },
{ en:"Inspection", abbr:"", ja:"視診", note:"外観・皮膚色・体型・呼吸パターンを観察する。", example:"Inspection showed abdominal distension.", cat:"diagnosis", level:"basic", dept:"GEN" },
{ en:"Murmur", abbr:"", ja:"心雑音", note:"収縮期/拡張期・Gradeで表現（1〜6/6）。", example:"A grade 3/6 systolic murmur was heard at the left sternal border.", cat:"diagnosis", level:"intermediate", dept:"GEN" },
{ en:"Rales", abbr:"", ja:"水泡音（ラ音）", note:"Crackles とも。肺水腫・肺炎で聴取。", example:"Fine rales were heard bilaterally at the lung bases.", cat:"diagnosis", level:"intermediate", dept:"GEN" },
{ en:"Wheezing", abbr:"", ja:"喘鳴（ウィーズ）", note:"気道狭窄音。喘息・COPDで聴取。", example:"Expiratory wheezing was heard throughout both lung fields.", cat:"diagnosis", level:"basic", dept:"GEN" },
{ en:"Bowel sounds", abbr:"BS", ja:"腸蠕動音", note:"正常・亢進・減弱・消失で表現。", example:"Bowel sounds are hypoactive in all four quadrants.", cat:"diagnosis", level:"basic", dept:"GEN" },
{ en:"Jaundice", abbr:"", ja:"黄疸", note:"ビリルビン上昇による皮膚・強膜の黄染。", example:"The patient has jaundice with scleral icterus.", cat:"symptom", level:"basic", dept:"GEN" },
{ en:"Cyanosis", abbr:"", ja:"チアノーゼ", note:"低酸素血症による皮膚・口唇の青紫色変化。", example:"Peripheral cyanosis was noted in the fingertips.", cat:"symptom", level:"basic", dept:"GEN" },
{ en:"Pallor", abbr:"", ja:"蒼白", note:"貧血・ショック・血管収縮で皮膚・粘膜が白くなる。", example:"The patient appeared pale and diaphoretic.", cat:"symptom", level:"basic", dept:"GEN" },
{ en:"Diaphoresis", abbr:"", ja:"発汗（冷汗）", note:"Cold / clammy skin とも。ACSのサイン。", example:"The patient was pale and diaphoretic on arrival.", cat:"symptom", level:"intermediate", dept:"GEN" },
{ en:"Edema", abbr:"", ja:"浮腫", note:"Pitting / Non-pitting。1+〜4+で重症度表現。", example:"Bilateral pitting edema was found up to the knees.", cat:"symptom", level:"intermediate", dept:"GEN" },
{ en:"Clubbing", abbr:"", ja:"ばち指", note:"慢性低酸素血症・肺疾患・先天性心疾患で生じる。", example:"Digital clubbing was noted — consistent with chronic hypoxia.", cat:"symptom", level:"intermediate", dept:"GEN" },

// ==================== 救急 ER ====================
{ en:"Triage", abbr:"", ja:"トリアージ", note:"重症度・緊急度による優先順位付け。START法が代表的。", example:"The patient was triaged as immediate on arrival.", cat:"common", level:"basic", dept:"ER" },
{ en:"Airway, Breathing, Circulation", abbr:"ABC", ja:"気道・呼吸・循環", note:"一次評価の基本。ABCDE評価（+ Disability, Exposure）。", example:"Primary survey: Airway patent, Breathing adequate, Circulation stable.", cat:"common", level:"basic", dept:"ER" },
{ en:"Resuscitation", abbr:"", ja:"蘇生", note:"心停止・ショックへの緊急対応。", example:"Resuscitation was initiated immediately upon arrival.", cat:"treatment", level:"basic", dept:"ER" },
{ en:"Cardiopulmonary resuscitation", abbr:"CPR", ja:"心肺蘇生", note:"胸骨圧迫30：人工呼吸2のサイクル。", example:"CPR was started immediately after the patient became unresponsive.", cat:"treatment", level:"basic", dept:"ER" },
{ en:"Defibrillation", abbr:"", ja:"除細動", note:"VF・pVTに対する電気的除細動。AEDも同原理。", example:"Defibrillation was delivered at 200 joules.", cat:"treatment", level:"intermediate", dept:"ER" },
{ en:"Shock", abbr:"", ja:"ショック", note:"組織灌流不全。Hypovolemic / Distributive / Cardiogenic / Obstructive に分類。", example:"The patient is in hypovolemic shock — start fluid resuscitation.", cat:"diagnosis", level:"intermediate", dept:"ER" },
{ en:"Hypotension", abbr:"", ja:"低血圧", note:"BP < 90/60 mmHg。ショックの徴候に注意。", example:"Hypotension persisted despite fluid resuscitation.", cat:"symptom", level:"basic", dept:"ER" },
{ en:"Syncope", abbr:"", ja:"失神", note:"Pre-syncope（失神前状態）と区別。起立性・心原性など。", example:"The patient experienced syncope while standing up.", cat:"symptom", level:"intermediate", dept:"ER" },
{ en:"Altered mental status", abbr:"AMS", ja:"意識変容", note:"錯乱・見当識障害・興奮・傾眠などを含む広義の意識障害。", example:"The patient presented with altered mental status and fever.", cat:"symptom", level:"intermediate", dept:"ER" },
{ en:"Loss of consciousness", abbr:"LOC", ja:"意識消失", note:"完全な意識の喪失。持続時間・回復状況を確認。", example:"The patient had a brief loss of consciousness lasting 30 seconds.", cat:"symptom", level:"basic", dept:"ER" },
{ en:"Trauma", abbr:"", ja:"外傷", note:"Blunt（鈍的）/ Penetrating（穿通）に分類。", example:"The patient was brought in after blunt trauma to the chest.", cat:"diagnosis", level:"basic", dept:"ER" },
{ en:"Mechanism of injury", abbr:"MOI", ja:"受傷機転", note:"どのようにして受傷したか。外傷評価の基本。", example:"What was the mechanism of injury?", cat:"common", level:"basic", dept:"ER" },
{ en:"Sepsis", abbr:"", ja:"敗血症", note:"感染症＋臓器障害。qSOFAスコアで評価。1時間バンドル開始。", example:"The patient met the criteria for sepsis.", cat:"diagnosis", level:"intermediate", dept:"ER" },
{ en:"Anaphylaxis", abbr:"", ja:"アナフィラキシー", note:"エピネフリン筋注が第一選択。遅延型に注意。", example:"The patient developed anaphylaxis after the bee sting.", cat:"diagnosis", level:"intermediate", dept:"ER" },
{ en:"Intubation", abbr:"ETT", ja:"気管内挿管", note:"RSI（rapid sequence intubation）で実施することが多い。", example:"The patient was intubated for airway protection.", cat:"treatment", level:"intermediate", dept:"ER" },
{ en:"Rapid sequence intubation", abbr:"RSI", ja:"迅速導入挿管", note:"鎮静薬＋筋弛緩薬を使用した安全な挿管法。", example:"RSI was performed using etomidate and succinylcholine.", cat:"treatment", level:"advanced", dept:"ER" },
{ en:"IV access", abbr:"IV", ja:"静脈路確保", note:"Large bore IV（太いカテーテル）が緊急時に必要。", example:"Two large-bore IV lines were established.", cat:"treatment", level:"basic", dept:"ER" },
{ en:"Fluid resuscitation", abbr:"", ja:"輸液蘇生", note:"Normal saline / Lactated Ringer'sが一般的。", example:"Fluid resuscitation was initiated with 1L of normal saline.", cat:"treatment", level:"intermediate", dept:"ER" },
{ en:"Blood culture", abbr:"BC", ja:"血液培養", note:"敗血症疑いで実施。2セット採取が原則。", example:"Blood cultures were drawn before starting antibiotics.", cat:"diagnosis", level:"intermediate", dept:"ER" },
{ en:"Laceration", abbr:"", ja:"裂傷", note:"鋭的・鈍的外力による皮膚裂け傷。縫合・ステープルで閉創。", example:"A 5 cm laceration on the forehead was sutured.", cat:"diagnosis", level:"basic", dept:"ER" },
{ en:"Suture", abbr:"", ja:"縫合", note:"Simple interrupted / Continuous / Mattressなど縫合法がある。", example:"The wound was closed with 4-0 nylon sutures.", cat:"treatment", level:"basic", dept:"ER" },
{ en:"Burn", abbr:"", ja:"熱傷", note:"深度（1〜3度）と面積（TBSA%）で評価。Rule of ninesを使用。", example:"The patient has a 20% TBSA burn involving the arms and chest.", cat:"diagnosis", level:"intermediate", dept:"ER" },
{ en:"Poison / Overdose", abbr:"OD", ja:"中毒・過量服薬", note:"Toxidrome（中毒症候群）を確認。毒物情報センターへ問い合わせ。", example:"The patient was brought in after a suspected overdose of acetaminophen.", cat:"diagnosis", level:"intermediate", dept:"ER" },
{ en:"Activated charcoal", abbr:"", ja:"活性炭", note:"経口摂取中毒の早期（1時間以内）に使用。", example:"Activated charcoal was administered for the oral overdose.", cat:"treatment", level:"intermediate", dept:"ER" },
{ en:"Point-of-care ultrasound", abbr:"POCUS", ja:"ポイントオブケア超音波", note:"ベッドサイドでの迅速超音波評価。FAST echo など。", example:"POCUS showed free fluid in the abdomen.", cat:"diagnosis", level:"intermediate", dept:"ER" },
{ en:"FAST exam", abbr:"FAST", ja:"外傷超音波迅速検査", note:"Focused Assessment with Sonography in Trauma。腹腔内出血・心嚢液を評価。", example:"FAST exam revealed free fluid in Morrison's pouch.", cat:"diagnosis", level:"intermediate", dept:"ER" },
{ en:"Do not resuscitate", abbr:"DNR", ja:"蘇生拒否", note:"患者・家族の意思に基づく心肺蘇生不実施の指示。", example:"The patient has a DNR order on file.", cat:"common", level:"intermediate", dept:"ER" },

// ==================== 内科 IM ====================
{ en:"Fever", abbr:"", ja:"発熱", note:">38.3°C を発熱と定義することが多い。", example:"The child has had a fever of 39°C for two days.", cat:"symptom", level:"basic", dept:"IM" },
{ en:"Chills", abbr:"", ja:"悪寒・戦慄", note:"Rigors（強い戦慄）は菌血症のサイン。", example:"The patient reports chills and high fever.", cat:"symptom", level:"basic", dept:"IM" },
{ en:"Night sweats", abbr:"", ja:"寝汗", note:"結核・リンパ腫・更年期などで生じる。", example:"She reports night sweats and unintentional weight loss.", cat:"symptom", level:"basic", dept:"IM" },
{ en:"Weight loss", abbr:"", ja:"体重減少", note:"6ヶ月で5%以上の体重減少が有意。悪性疾患・消耗性疾患を示唆。", example:"He has lost 5 kg over the past 3 months without trying.", cat:"symptom", level:"basic", dept:"IM" },
{ en:"Fatigue", abbr:"", ja:"倦怠感", note:"全身の疲れ・だるさ。貧血・甲状腺機能低下症など多くの疾患で出現。", example:"She complains of extreme fatigue for the past month.", cat:"symptom", level:"basic", dept:"IM" },
{ en:"Anorexia", abbr:"", ja:"食欲不振", note:"食欲の低下または消失。悪性疾患・うつ病・消化器疾患で多い。", example:"The patient reports anorexia and has not eaten for two days.", cat:"symptom", level:"basic", dept:"IM" },
{ en:"Diabetes mellitus", abbr:"DM", ja:"糖尿病", note:"Type 1 / Type 2。HbA1cで管理目標を設定。", example:"He has a 10-year history of type 2 diabetes mellitus.", cat:"diagnosis", level:"basic", dept:"IM" },
{ en:"Hyperglycemia", abbr:"", ja:"高血糖", note:"FBG >126 mg/dL、または随時血糖 >200 mg/dL。", example:"The patient presented with hyperglycemia and altered mental status.", cat:"symptom", level:"basic", dept:"IM" },
{ en:"Hypoglycemia", abbr:"", ja:"低血糖", note:"BG <70 mg/dL。発汗・動悸・意識障害が出現。", example:"The patient had a hypoglycemic episode — BG was 45 mg/dL.", cat:"symptom", level:"basic", dept:"IM" },
{ en:"Hypothyroidism", abbr:"", ja:"甲状腺機能低下症", note:"TSH上昇・FT4低下。倦怠感・体重増加・便秘が主症状。", example:"TSH was elevated at 15 mIU/L, consistent with hypothyroidism.", cat:"diagnosis", level:"intermediate", dept:"IM" },
{ en:"Hyperthyroidism", abbr:"", ja:"甲状腺機能亢進症", note:"TSH低下・FT4/T3上昇。動悸・発汗・体重減少が主症状。", example:"The patient has hyperthyroidism with a palpable goiter.", cat:"diagnosis", level:"intermediate", dept:"IM" },
{ en:"Anemia", abbr:"", ja:"貧血", note:"Hgb: 男性<13 g/dL、女性<12 g/dL。Iron deficiency が最多。", example:"CBC revealed anemia with a hemoglobin of 8.5 g/dL.", cat:"diagnosis", level:"basic", dept:"IM" },
{ en:"Thrombocytopenia", abbr:"", ja:"血小板減少症", note:"Plt <150,000/μL。出血傾向に注意。", example:"Thrombocytopenia was found with a platelet count of 50,000.", cat:"diagnosis", level:"intermediate", dept:"IM" },
{ en:"Leukocytosis", abbr:"", ja:"白血球増多症", note:"WBC >11,000/μL。感染・炎症・白血病など。", example:"Leukocytosis with left shift suggests bacterial infection.", cat:"diagnosis", level:"intermediate", dept:"IM" },
{ en:"Urinary tract infection", abbr:"UTI", ja:"尿路感染症", note:"排尿痛・頻尿・混濁尿。女性に多い。尿検査・培養で確認。", example:"Urinalysis confirmed a urinary tract infection.", cat:"diagnosis", level:"basic", dept:"IM" },
{ en:"Kidney stones", abbr:"", ja:"尿路結石", note:"Renal calculi / Nephrolithiasis。側腹部の疝痛発作が特徴。", example:"CT showed a 6 mm kidney stone in the right ureter.", cat:"diagnosis", level:"basic", dept:"IM" },
{ en:"Acute kidney injury", abbr:"AKI", ja:"急性腎障害", note:"Creatinine の急激な上昇。Pre-renal / Renal / Post-renalに分類。", example:"The patient developed acute kidney injury with rising creatinine.", cat:"diagnosis", level:"intermediate", dept:"IM" },
{ en:"Chronic kidney disease", abbr:"CKD", ja:"慢性腎臓病", note:"eGFR <60 mL/min/1.73m² が3ヶ月以上持続。Stage 1〜5。", example:"She has CKD stage 3 with an eGFR of 45.", cat:"diagnosis", level:"intermediate", dept:"IM" },
{ en:"Liver function tests", abbr:"LFTs", ja:"肝機能検査", note:"AST・ALT・ALP・GGT・T-Bil・Albumin を含む。", example:"LFTs showed elevated transaminases — AST 180, ALT 220.", cat:"diagnosis", level:"basic", dept:"IM" },
{ en:"Cirrhosis", abbr:"", ja:"肝硬変", note:"慢性肝疾患の終末像。腹水・静脈瘤・脳症の三徴。", example:"The patient has alcoholic cirrhosis with ascites.", cat:"diagnosis", level:"intermediate", dept:"IM" },
{ en:"Ascites", abbr:"", ja:"腹水", note:"腹腔内への液体貯留。肝硬変・悪性腫瘍・心不全で多い。", example:"Ultrasound confirmed a large amount of ascites.", cat:"symptom", level:"intermediate", dept:"IM" },
{ en:"CBC", abbr:"", ja:"全血球計算", note:"Complete Blood Count。WBC・RBC・Hgb・Hct・Plt を含む。", example:"CBC showed leukocytosis with a left shift.", cat:"diagnosis", level:"basic", dept:"IM" },
{ en:"BMP", abbr:"", ja:"基礎代謝パネル", note:"Basic Metabolic Panel。Na・K・Cl・CO2・BUN・Cr・Glc。", example:"BMP revealed hyponatremia and elevated creatinine.", cat:"diagnosis", level:"intermediate", dept:"IM" },
{ en:"HbA1c", abbr:"", ja:"ヘモグロビンA1c", note:"過去2〜3ヶ月の血糖コントロール指標。目標 <7%。", example:"HbA1c was 9.2%, indicating poor glycemic control.", cat:"diagnosis", level:"basic", dept:"IM" },
{ en:"NPO", abbr:"", ja:"絶食", note:"Nothing by mouth。手術前・嚥下障害時に指示。", example:"Keep the patient NPO after midnight.", cat:"treatment", level:"basic", dept:"IM" },
{ en:"PRN", abbr:"", ja:"必要時", note:"Pro re nata（ラテン語）。症状に応じて投与。", example:"Acetaminophen 500mg PRN for pain.", cat:"treatment", level:"basic", dept:"IM" },
{ en:"Discharge", abbr:"DC", ja:"退院・帰宅", note:"Admit（入院）の対語。DC summaryを記載する。", example:"The patient is stable for discharge tomorrow.", cat:"treatment", level:"basic", dept:"IM" },

// ==================== 循環器 CV ====================
{ en:"Chest pain", abbr:"CP", ja:"胸痛", note:"OPQRST で評価。ACS・PE・気胸・大動脈解離を除外。", example:"The patient presents with chest pain and diaphoresis.", cat:"symptom", level:"basic", dept:"CV" },
{ en:"Myocardial infarction", abbr:"MI", ja:"心筋梗塞", note:"STEMI / NSTEMIに分類。Troponin上昇が診断の鍵。", example:"The patient presented with classic signs of MI.", cat:"diagnosis", level:"basic", dept:"CV" },
{ en:"Angina pectoris", abbr:"", ja:"狭心症", note:"Stable / Unstable / Variantで分類。", example:"He has a history of stable angina pectoris.", cat:"symptom", level:"intermediate", dept:"CV" },
{ en:"Heart failure", abbr:"HF", ja:"心不全", note:"EF保持型(HFpEF) / 低下型(HFrEF)。", example:"She was admitted for acute decompensated heart failure.", cat:"diagnosis", level:"intermediate", dept:"CV" },
{ en:"Hypertension", abbr:"HTN", ja:"高血圧", note:"BP ≥ 130/80 mmHg (AHA 2017基準)。", example:"He has a history of hypertension, controlled with medication.", cat:"diagnosis", level:"basic", dept:"CV" },
{ en:"Tachycardia", abbr:"", ja:"頻脈", note:"HR > 100 bpm。発熱・貧血・不安など多くの原因がある。", example:"Sinus tachycardia was noted on the ECG.", cat:"symptom", level:"basic", dept:"CV" },
{ en:"Bradycardia", abbr:"", ja:"徐脈", note:"HR < 60 bpm。β遮断薬・迷走神経反射など。", example:"The patient developed bradycardia after the medication.", cat:"symptom", level:"basic", dept:"CV" },
{ en:"Atrial fibrillation", abbr:"AFib", ja:"心房細動", note:"不規則脈・脳梗塞リスク。CHADS2スコアで抗凝固適応評価。", example:"The patient was found to be in atrial fibrillation with rapid ventricular response.", cat:"diagnosis", level:"intermediate", dept:"CV" },
{ en:"Ventricular fibrillation", abbr:"VF", ja:"心室細動", note:"心停止に相当。直ちに除細動が必要。", example:"The patient went into ventricular fibrillation and required defibrillation.", cat:"diagnosis", level:"intermediate", dept:"CV" },
{ en:"ST elevation", abbr:"STE", ja:"ST上昇", note:"STEMI の診断基準。緊急PCIの適応。", example:"ST elevation in leads II, III, aVF suggests inferior STEMI.", cat:"diagnosis", level:"intermediate", dept:"CV" },
{ en:"Troponin", abbr:"", ja:"トロポニン", note:"心筋障害のマーカー。High-sensitivity troponin で早期診断。", example:"Serial troponins were drawn — first value was 0.8 ng/mL.", cat:"diagnosis", level:"basic", dept:"CV" },
{ en:"BNP", abbr:"BNP", ja:"脳性ナトリウム利尿ペプチド", note:"心不全の診断・重症度評価。>100 pg/mL が目安。", example:"BNP was markedly elevated at 1200 pg/mL.", cat:"diagnosis", level:"intermediate", dept:"CV" },
{ en:"ECG", abbr:"ECG", ja:"心電図", note:"12誘導が標準。リズム・ST変化・QTcを評価。", example:"A 12-lead ECG was performed immediately.", cat:"diagnosis", level:"basic", dept:"CV" },
{ en:"Echocardiogram", abbr:"Echo", ja:"心臓超音波検査", note:"壁運動・弁・EF・心嚢液を評価。TTE / TEEがある。", example:"Echocardiogram showed an ejection fraction of 35%.", cat:"diagnosis", level:"intermediate", dept:"CV" },
{ en:"Palpitation", abbr:"", ja:"動悸", note:"Irregular / rapid / forcefulなど性状を確認。", example:"She reports palpitations lasting several seconds.", cat:"symptom", level:"basic", dept:"CV" },
{ en:"Ejection fraction", abbr:"EF", ja:"駆出率", note:"心室が1回の収縮で拍出する血液の割合。正常 >55%。", example:"The echocardiogram showed a reduced ejection fraction of 30%.", cat:"diagnosis", level:"intermediate", dept:"CV" },
{ en:"Peripheral artery disease", abbr:"PAD", ja:"末梢動脈疾患", note:"ABI（足関節上腕血圧比）<0.9で診断。間欠性跛行が主症状。", example:"ABI was 0.6, confirming peripheral artery disease.", cat:"diagnosis", level:"intermediate", dept:"CV" },
{ en:"Deep vein thrombosis", abbr:"DVT", ja:"深部静脈血栓症", note:"下肢腫脹・疼痛・発赤。Homan's signは感度低い。超音波で確認。", example:"Doppler ultrasound confirmed a DVT in the left femoral vein.", cat:"diagnosis", level:"intermediate", dept:"CV" },
{ en:"Pulmonary embolism", abbr:"PE", ja:"肺塞栓症", note:"突然の呼吸困難・胸痛・頻脈。Wells スコアで事前確率評価。", example:"CT pulmonary angiography confirmed a massive pulmonary embolism.", cat:"diagnosis", level:"intermediate", dept:"CV" },
{ en:"Anticoagulation", abbr:"", ja:"抗凝固療法", note:"DVT・PE・AFibに対して実施。Heparin / DOAC / Warfarin。", example:"Anticoagulation was started with low molecular weight heparin.", cat:"treatment", level:"intermediate", dept:"CV" },
{ en:"Nitroglycerin", abbr:"NTG", ja:"ニトログリセリン", note:"狭心症発作・高血圧緊急症に使用。舌下錠・スプレー。低血圧に注意。", example:"Nitroglycerin was given sublingually for chest pain relief.", cat:"treatment", level:"intermediate", dept:"CV" },
{ en:"Diaphoresis", abbr:"", ja:"発汗（冷汗）", note:"ACSの重要な随伴症状。Cold / clammy skinとも表現。", example:"The patient was pale and diaphoretic — ACS was suspected.", cat:"symptom", level:"intermediate", dept:"CV" },

// ==================== 呼吸器 RESP ====================
{ en:"Dyspnea", abbr:"SOB", ja:"呼吸困難", note:"Shortness of breath とも。労作時・安静時を区別する。", example:"The patient complains of dyspnea on exertion.", cat:"symptom", level:"basic", dept:"RESP" },
{ en:"Cough", abbr:"", ja:"咳嗽", note:"Dry（乾性）/ Productive（湿性）を区別。性状・持続期間を確認。", example:"She has had a productive cough with yellow sputum for 5 days.", cat:"symptom", level:"basic", dept:"RESP" },
{ en:"Sputum", abbr:"", ja:"喀痰", note:"色・量・性状を確認。Purulent（膿性）は細菌感染を示唆。", example:"The sputum is purulent and green in color.", cat:"symptom", level:"basic", dept:"RESP" },
{ en:"Hemoptysis", abbr:"", ja:"喀血", note:"Hematemesis（吐血）と混同しないこと。", example:"Hemoptysis may indicate tuberculosis or lung cancer.", cat:"symptom", level:"intermediate", dept:"RESP" },
{ en:"Pneumonia", abbr:"PNA", ja:"肺炎", note:"CAP（市中）/ HAP（院内）/ VAP（人工呼吸器関連）。", example:"Community-acquired pneumonia was confirmed by chest X-ray.", cat:"diagnosis", level:"basic", dept:"RESP" },
{ en:"Asthma", abbr:"", ja:"喘息", note:"Wheezing・呼吸困難・咳が三徴。Peak flowで評価。", example:"The child was brought in with an acute asthma attack.", cat:"diagnosis", level:"basic", dept:"RESP" },
{ en:"COPD", abbr:"COPD", ja:"慢性閉塞性肺疾患", note:"Chronic Obstructive Pulmonary Disease。喫煙歴が重要。", example:"COPD exacerbation was treated with bronchodilators.", cat:"diagnosis", level:"intermediate", dept:"RESP" },
{ en:"Pleural effusion", abbr:"", ja:"胸水", note:"Transudate / Exudate をLight's criteriaで鑑別。", example:"Chest X-ray showed a large right pleural effusion.", cat:"diagnosis", level:"intermediate", dept:"RESP" },
{ en:"Pneumothorax", abbr:"PTX", ja:"気胸", note:"自然気胸・外傷性気胸・緊張性気胸に分類。緊張性は緊急処置。", example:"Tension pneumothorax was relieved by needle decompression.", cat:"diagnosis", level:"intermediate", dept:"RESP" },
{ en:"Pulmonary fibrosis", abbr:"IPF", ja:"肺線維症", note:"進行性の肺実質線維化。Velcro ralesが特徴的。", example:"HRCT confirmed the diagnosis of idiopathic pulmonary fibrosis.", cat:"diagnosis", level:"advanced", dept:"RESP" },
{ en:"Oxygen therapy", abbr:"O2", ja:"酸素療法", note:"Nasal cannula / Face mask / Non-rebreather / Ventilatorで投与。", example:"Oxygen was started at 4L/min via nasal cannula.", cat:"treatment", level:"basic", dept:"RESP" },
{ en:"Bronchodilator", abbr:"", ja:"気管支拡張薬", note:"Salbutamol / Ipratropium など。喘息・COPD急性増悪に使用。", example:"A bronchodilator nebulizer was administered for the asthma attack.", cat:"treatment", level:"basic", dept:"RESP" },
{ en:"Incentive spirometry", abbr:"IS", ja:"インセンティブ・スパイロメトリー", note:"術後の肺合併症予防に使用。深呼吸訓練。", example:"The patient was instructed to use incentive spirometry every hour.", cat:"treatment", level:"basic", dept:"RESP" },
{ en:"Peak flow", abbr:"PEFR", ja:"最大呼気流量", note:"喘息の重症度評価・モニタリングに使用。", example:"Peak flow was 60% of predicted — a moderate asthma attack.", cat:"diagnosis", level:"intermediate", dept:"RESP" },
{ en:"Chest X-ray", abbr:"CXR", ja:"胸部X線", note:"肺炎・胸水・気胸・心拡大などを評価。PA / AP viewがある。", example:"Chest X-ray showed bilateral infiltrates consistent with pneumonia.", cat:"diagnosis", level:"basic", dept:"RESP" },
{ en:"CT pulmonary angiography", abbr:"CTPA", ja:"CT肺動脈造影", note:"肺塞栓症の標準的画像診断。Goldstandard。", example:"CTPA confirmed bilateral pulmonary emboli.", cat:"diagnosis", level:"intermediate", dept:"RESP" },
{ en:"Spirometry", abbr:"", ja:"スパイロメトリー", note:"FEV1 / FVC で閉塞性・拘束性換気障害を鑑別。", example:"Spirometry showed an obstructive pattern consistent with COPD.", cat:"diagnosis", level:"intermediate", dept:"RESP" },
{ en:"Tachypnea", abbr:"", ja:"頻呼吸", note:"RR > 20回/分。呼吸障害・アシドーシスの代償。", example:"Tachypnea with RR of 28 was noted on examination.", cat:"symptom", level:"basic", dept:"RESP" },
{ en:"Respiratory failure", abbr:"", ja:"呼吸不全", note:"Type 1（低酸素）/ Type 2（高CO2）に分類。", example:"The patient developed type 2 respiratory failure requiring ventilatory support.", cat:"diagnosis", level:"intermediate", dept:"RESP" },
{ en:"Mechanical ventilation", abbr:"MV", ja:"人工呼吸管理", note:"侵襲的（ETT）/ 非侵襲的（NPPV/BiPAP）がある。", example:"The patient was placed on mechanical ventilation after intubation.", cat:"treatment", level:"advanced", dept:"RESP" },

// ==================== 消化器 GI ====================
{ en:"Nausea / Vomiting", abbr:"N/V", ja:"悪心／嘔吐", note:"N/V と略記。回数・性状・血液混入を確認。", example:"She reports nausea and vomiting for 2 days.", cat:"symptom", level:"basic", dept:"GI" },
{ en:"Abdominal pain", abbr:"", ja:"腹痛", note:"部位・性状・放散・随伴症状で鑑別。OPQRST で評価。", example:"The patient has severe abdominal pain in the right lower quadrant.", cat:"symptom", level:"basic", dept:"GI" },
{ en:"Diarrhea", abbr:"", ja:"下痢", note:"Watery / Bloody / Mucoid で表現。回数・持続期間を確認。", example:"The patient has had watery diarrhea 8 times today.", cat:"symptom", level:"basic", dept:"GI" },
{ en:"Constipation", abbr:"", ja:"便秘", note:"3日以上の排便なし。腸閉塞との鑑別が重要。", example:"The patient has not had a bowel movement in 5 days.", cat:"symptom", level:"basic", dept:"GI" },
{ en:"Melena", abbr:"", ja:"黒色便（タール便）", note:"上部消化管出血のサイン。Hgb分解産物による。", example:"The patient passed tarry black stools — melena was noted.", cat:"symptom", level:"intermediate", dept:"GI" },
{ en:"Hematochezia", abbr:"", ja:"血便（鮮血便）", note:"下部消化管出血のサイン。直腸・S状結腸の出血で多い。", example:"Hematochezia was reported — colonoscopy was ordered.", cat:"symptom", level:"intermediate", dept:"GI" },
{ en:"Appendicitis", abbr:"", ja:"虫垂炎", note:"McBurney点・Rebound tendernessが所見。Alvaradoスコアで評価。", example:"The patient presented with right lower quadrant pain, suspect appendicitis.", cat:"diagnosis", level:"basic", dept:"GI" },
{ en:"Cholecystitis", abbr:"", ja:"胆嚢炎", note:"Murphy's sign 陽性。超音波で確認。右上腹部痛が特徴。", example:"Acute cholecystitis was confirmed by ultrasound.", cat:"diagnosis", level:"intermediate", dept:"GI" },
{ en:"Pancreatitis", abbr:"", ja:"膵炎", note:"Lipase上昇・上腹部痛・背部放散痛。Ranson基準で重症度評価。", example:"Serum lipase was 1200 U/L, confirming acute pancreatitis.", cat:"diagnosis", level:"intermediate", dept:"GI" },
{ en:"Peptic ulcer disease", abbr:"PUD", ja:"消化性潰瘍", note:"胃・十二指腸潰瘍。H. pylori・NSAIDsが主な原因。", example:"Endoscopy revealed a 1.5 cm peptic ulcer in the duodenum.", cat:"diagnosis", level:"intermediate", dept:"GI" },
{ en:"Gastroesophageal reflux", abbr:"GERD", ja:"胃食道逆流症", note:"胸やけ・逆流感が特徴。PPI が第一選択。", example:"She has a long history of GERD managed with omeprazole.", cat:"diagnosis", level:"basic", dept:"GI" },
{ en:"Ileus", abbr:"", ja:"腸閉塞（麻痺性・機械的）", note:"Paralytic（機能的）/ Mechanical（器質的）に分類。", example:"Post-operative ileus was managed conservatively.", cat:"diagnosis", level:"intermediate", dept:"GI" },
{ en:"Rebound tenderness", abbr:"", ja:"反跳痛（ブルンベルグ徴候）", note:"腹膜炎のサイン。圧を離したときに痛みが増強。", example:"Rebound tenderness was present in the right lower quadrant.", cat:"diagnosis", level:"intermediate", dept:"GI" },
{ en:"Guarding", abbr:"", ja:"筋性防御", note:"腹膜刺激による腹壁筋の不随意収縮。腹膜炎のサイン。", example:"Involuntary guarding was noted on abdominal examination.", cat:"diagnosis", level:"intermediate", dept:"GI" },
{ en:"Colonoscopy", abbr:"", ja:"大腸内視鏡検査", note:"大腸がん・炎症性腸疾患・ポリープの診断に使用。", example:"Colonoscopy revealed a polyp in the sigmoid colon.", cat:"diagnosis", level:"basic", dept:"GI" },
{ en:"Endoscopy", abbr:"EGD", ja:"上部消化管内視鏡検査", note:"食道・胃・十二指腸を観察。EGD (Esophagogastroduodenoscopy)。", example:"EGD showed active bleeding from a gastric ulcer.", cat:"diagnosis", level:"basic", dept:"GI" },

// ==================== 脳神経 NEURO ====================
{ en:"Stroke", abbr:"CVA", ja:"脳卒中", note:"Cerebrovascular accident。FAST（顔・腕・言語・時間）で評価。", example:"The patient was brought in with signs of stroke.", cat:"diagnosis", level:"basic", dept:"NEURO" },
{ en:"TIA", abbr:"TIA", ja:"一過性脳虚血発作", note:"Transient Ischemic Attack。24時間以内に症状消失。Mini-strokeとも。", example:"She was admitted for evaluation after a suspected TIA.", cat:"diagnosis", level:"intermediate", dept:"NEURO" },
{ en:"Seizure", abbr:"", ja:"痙攣", note:"Tonic-clonic / Absence / Focal など種類がある。", example:"The patient had a generalized tonic-clonic seizure.", cat:"symptom", level:"intermediate", dept:"NEURO" },
{ en:"Headache", abbr:"HA", ja:"頭痛", note:"Thunderclap（くも膜下出血）/ Migraine / Tension type で鑑別。", example:"He presents with the worst headache of his life.", cat:"symptom", level:"basic", dept:"NEURO" },
{ en:"Dizziness", abbr:"", ja:"めまい", note:"Vertigo（回転性）/ Presyncope（立ちくらみ）/ Disequilibrium（平衡障害）を区別。", example:"She reports sudden onset rotatory dizziness.", cat:"symptom", level:"basic", dept:"NEURO" },
{ en:"Aphasia", abbr:"", ja:"失語症", note:"Broca（運動性）/ Wernicke（感覚性）に分類。脳卒中・腫瘍で出現。", example:"The patient has expressive aphasia and cannot speak clearly.", cat:"symptom", level:"intermediate", dept:"NEURO" },
{ en:"Hemiplegia", abbr:"", ja:"片麻痺", note:"一側の上下肢麻痺。脳卒中の代表的症状。", example:"Right hemiplegia was noted following the ischemic stroke.", cat:"symptom", level:"intermediate", dept:"NEURO" },
{ en:"Numbness", abbr:"", ja:"しびれ・感覚消失", note:"Paresthesia（異常感覚）とも。デルマトーム分布で神経障害部位を推定。", example:"The patient reports numbness in the left arm and face.", cat:"symptom", level:"basic", dept:"NEURO" },
{ en:"Meningitis", abbr:"", ja:"髄膜炎", note:"頭痛・発熱・項部硬直の三徴。腰椎穿刺で確定診断。", example:"Nuchal rigidity and fever raised concern for bacterial meningitis.", cat:"diagnosis", level:"intermediate", dept:"NEURO" },
{ en:"Intracranial hemorrhage", abbr:"ICH", ja:"頭蓋内出血", note:"Epidural / Subdural / Subarachnoid / Intracerebral に分類。", example:"Non-contrast CT showed a large intracerebral hemorrhage.", cat:"diagnosis", level:"intermediate", dept:"NEURO" },
{ en:"Lumbar puncture", abbr:"LP", ja:"腰椎穿刺", note:"髄液検査。髄膜炎・くも膜下出血の確定診断に使用。", example:"Lumbar puncture was performed to rule out meningitis.", cat:"diagnosis", level:"intermediate", dept:"NEURO" },
{ en:"MRI brain", abbr:"MRI", ja:"頭部MRI", note:"脳梗塞・腫瘍・MS・出血などの評価に使用。CTより感度高い。", example:"MRI brain showed a new ischemic lesion in the left MCA territory.", cat:"diagnosis", level:"basic", dept:"NEURO" },

// ==================== 整形外科 ORTHO ====================
{ en:"Fracture", abbr:"Fx", ja:"骨折", note:"Open（開放）/ Closed（閉鎖）/ Displaced（転位）。", example:"X-ray confirmed a displaced fracture of the radius.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Dislocation", abbr:"", ja:"脱臼", note:"Shoulder dislocationが最多。整復後X線確認。", example:"The shoulder dislocation was reduced in the ER.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Comminuted fracture", abbr:"", ja:"粉砕骨折", note:"骨が3片以上に砕けた骨折。高エネルギー外傷に多い。", example:"A comminuted fracture of the femur was seen on X-ray.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Stress fracture", abbr:"", ja:"疲労骨折", note:"繰り返しの負荷による骨折。ランナー・スポーツ選手に多い。", example:"An MRI confirmed a stress fracture of the tibia.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Avulsion fracture", abbr:"", ja:"剥離骨折", note:"靭帯・腱の牽引力で骨片が剥がれる骨折。", example:"An avulsion fracture at the base of the fifth metatarsal was noted.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Colles' fracture", abbr:"", ja:"コーレス骨折", note:"橈骨遠位端骨折。転倒時に手をついて受傷。高齢女性に多い。", example:"She sustained a Colles' fracture after a fall on an outstretched hand.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Hip fracture", abbr:"", ja:"大腿骨近位部骨折", note:"頸部骨折・転子部骨折に分類。高齢者の転倒で多発。", example:"The elderly patient was admitted with a hip fracture after a fall.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Vertebral compression fracture", abbr:"VCF", ja:"脊椎圧迫骨折", note:"骨粗鬆症性が最多。背部痛・身長低下が主訴。", example:"MRI revealed a new vertebral compression fracture at L1.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Open fracture", abbr:"", ja:"開放骨折", note:"骨が皮膚を貫通。感染リスク高。Gustilo分類で重症度評価。", example:"The open fracture required urgent irrigation and debridement.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Herniated disc", abbr:"HNP", ja:"椎間板ヘルニア", note:"Herniated Nucleus Pulposus。L4/5・L5/S1が好発部位。", example:"MRI showed a herniated disc at L4-L5 compressing the nerve root.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Spinal stenosis", abbr:"", ja:"脊柱管狭窄症", note:"神経性間欠跛行が特徴。前屈みで症状緩和。", example:"The patient has lumbar spinal stenosis causing neurogenic claudication.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Spondylolisthesis", abbr:"", ja:"脊椎すべり症", note:"上位椎体が前方にずれる。腰痛・下肢放散痛を呈する。", example:"Grade II spondylolisthesis was found at L5-S1.", cat:"diagnosis", level:"advanced", dept:"ORTHO" },
{ en:"Scoliosis", abbr:"", ja:"脊柱側弯症", note:"Cobb角10°以上。思春期特発性が最多。", example:"Adolescent idiopathic scoliosis with a Cobb angle of 35 degrees.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Cervical myelopathy", abbr:"", ja:"頸髄症", note:"頸部脊髄の圧迫。手指巧緻運動障害・歩行障害が主症状。", example:"The patient presented with cervical myelopathy and hand clumsiness.", cat:"diagnosis", level:"advanced", dept:"ORTHO" },
{ en:"Radiculopathy", abbr:"", ja:"神経根症", note:"神経根の圧迫。デルマトームに沿った放散痛・しびれ。", example:"Right L5 radiculopathy was confirmed by nerve conduction study.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Osteoarthritis", abbr:"OA", ja:"変形性関節症", note:"軟骨の摩耗による関節変性。膝・股関節・手指に多い。", example:"The patient has severe knee osteoarthritis requiring joint replacement.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Rheumatoid arthritis", abbr:"RA", ja:"関節リウマチ", note:"自己免疫疾患。朝のこわばり・対称性多関節炎が特徴。", example:"She has a 10-year history of rheumatoid arthritis.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Rotator cuff tear", abbr:"RCT", ja:"腱板断裂", note:"棘上筋腱が最多。肩の疼痛・外転筋力低下。MRIで確認。", example:"MRI confirmed a full-thickness rotator cuff tear.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"ACL tear", abbr:"ACL", ja:"前十字靭帯断裂", note:"Anterior Cruciate Ligament。スポーツ外傷で多い。Lachman test陽性。", example:"The athlete suffered an ACL tear during the game.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Meniscus tear", abbr:"", ja:"半月板損傷", note:"内側が外側より多い。McMurray test で評価。", example:"Arthroscopy confirmed a medial meniscus tear.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Carpal tunnel syndrome", abbr:"CTS", ja:"手根管症候群", note:"正中神経の圧迫。夜間のしびれ・Tinel's sign陽性。", example:"Carpal tunnel syndrome was confirmed by nerve conduction study.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Tennis elbow", abbr:"", ja:"テニス肘（外側上顆炎）", note:"前腕伸筋の起始部炎症。Cozen's test陽性。", example:"He was diagnosed with lateral epicondylitis from repetitive motion.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Trigger finger", abbr:"", ja:"ばね指", note:"腱鞘炎による屈曲腱の引っかかり。弾発現象が特徴。", example:"The patient has a trigger finger in the right ring finger.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Adhesive capsulitis", abbr:"", ja:"凍結肩（五十肩）", note:"Frozen shoulder。肩関節可動域制限・疼痛。", example:"She was diagnosed with adhesive capsulitis of the left shoulder.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Range of motion", abbr:"ROM", ja:"関節可動域", note:"Active ROM / Passive ROMで評価。角度で記録。", example:"ROM of the knee is limited to 90 degrees of flexion.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Crepitus", abbr:"", ja:"軋轢音（クレピタス）", note:"関節や骨折部の摩擦音。変形性関節症・骨折部位で触知。", example:"Crepitus was noted on passive movement of the knee.", cat:"symptom", level:"intermediate", dept:"ORTHO" },
{ en:"Tenderness", abbr:"", ja:"圧痛", note:"Point tenderness = 局所圧痛。骨折・炎症部位の診察所見。", example:"There is point tenderness over the lateral malleolus.", cat:"symptom", level:"basic", dept:"ORTHO" },
{ en:"Muscle atrophy", abbr:"", ja:"筋萎縮", note:"廃用・神経障害による筋肉量低下。周径測定で評価。", example:"Significant quadriceps atrophy was noted after prolonged immobilization.", cat:"symptom", level:"intermediate", dept:"ORTHO" },
{ en:"Paresthesia", abbr:"", ja:"異常感覚（しびれ）", note:"Tingling / Numbness / Burning sensation で表現。", example:"The patient reports paresthesia in the thumb and index finger.", cat:"symptom", level:"intermediate", dept:"ORTHO" },
{ en:"Locking", abbr:"", ja:"ロッキング（関節絞扼）", note:"関節が動かなくなる現象。半月板損傷・遊離体で起こる。", example:"The patient experienced locking of the knee joint.", cat:"symptom", level:"intermediate", dept:"ORTHO" },
{ en:"Giving way", abbr:"", ja:"膝くずれ", note:"関節の突然の力抜け。靭帯損傷・膝蓋骨不安定性で起こる。", example:"She reports giving way of the knee when going down stairs.", cat:"symptom", level:"intermediate", dept:"ORTHO" },
{ en:"Total knee replacement", abbr:"TKR", ja:"人工膝関節全置換術", note:"TKA とも。末期OAの根治的治療。", example:"The patient underwent total knee replacement for end-stage osteoarthritis.", cat:"treatment", level:"intermediate", dept:"ORTHO" },
{ en:"Total hip replacement", abbr:"THR", ja:"人工股関節全置換術", note:"THA とも。脱臼予防姿勢指導が重要。", example:"Total hip replacement was performed for avascular necrosis.", cat:"treatment", level:"intermediate", dept:"ORTHO" },
{ en:"Arthroscopy", abbr:"", ja:"関節鏡手術", note:"低侵襲。半月板・靭帯・腱板の修復に使用。", example:"Arthroscopic repair of the ACL was performed successfully.", cat:"treatment", level:"intermediate", dept:"ORTHO" },
{ en:"Open reduction internal fixation", abbr:"ORIF", ja:"観血的整復内固定術", note:"骨折の手術的整復。プレート・スクリューで固定。", example:"ORIF was performed for the displaced femoral neck fracture.", cat:"treatment", level:"intermediate", dept:"ORTHO" },
{ en:"Casting", abbr:"", ja:"ギプス固定", note:"Short arm cast / Long leg cast など部位で表現。", example:"A short arm cast was applied for the wrist fracture.", cat:"treatment", level:"basic", dept:"ORTHO" },
{ en:"Splinting", abbr:"", ja:"シーネ固定", note:"腫脹がある急性期に使用。ギプスより圧迫が少ない。", example:"A posterior splint was applied until swelling subsided.", cat:"treatment", level:"basic", dept:"ORTHO" },
{ en:"Traction", abbr:"", ja:"牽引療法", note:"骨折の整復・脊椎疾患の除圧目的。", example:"Skin traction was applied to reduce muscle spasm.", cat:"treatment", level:"intermediate", dept:"ORTHO" },
{ en:"Physical therapy", abbr:"PT", ja:"理学療法", note:"ROM訓練・筋力強化・歩行訓練など。術後リハビリの中心。", example:"Physical therapy was initiated on postoperative day 1.", cat:"treatment", level:"basic", dept:"ORTHO" },
{ en:"Weight bearing", abbr:"WB", ja:"荷重", note:"NWB（非荷重）/ PWB（部分荷重）/ FWB（全荷重）で指示。", example:"The patient was instructed to remain non-weight bearing for 6 weeks.", cat:"treatment", level:"basic", dept:"ORTHO" },
{ en:"DVT prophylaxis", abbr:"", ja:"深部静脈血栓予防", note:"術後の重要な合併症予防。抗凝固薬・弾性ストッキング・早期離床。", example:"DVT prophylaxis with LMWH was started postoperatively.", cat:"treatment", level:"intermediate", dept:"ORTHO" },
{ en:"Bone density", abbr:"BMD", ja:"骨密度", note:"DXAスキャンで測定。T-score ≤ -2.5 で骨粗鬆症。", example:"Bone density scan showed osteoporosis with a T-score of -3.1.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Osteoporosis", abbr:"", ja:"骨粗鬆症", note:"骨密度低下・骨折リスク増大。T-score ≤ -2.5。", example:"She was started on bisphosphonate therapy for osteoporosis.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Compartment syndrome", abbr:"", ja:"コンパートメント症候群", note:"6P（Pain・Pressure・Paresthesia・Paralysis・Pallor・Pulselessness）。緊急減張切開が必要。", example:"Compartment syndrome was suspected and urgent fasciotomy was performed.", cat:"diagnosis", level:"advanced", dept:"ORTHO" },
{ en:"Avascular necrosis", abbr:"AVN", ja:"無腐性壊死（骨壊死）", note:"血流途絶による骨壊死。大腿骨頭に多い。ステロイド・アルコールが危険因子。", example:"MRI confirmed avascular necrosis of the femoral head.", cat:"diagnosis", level:"advanced", dept:"ORTHO" },
{ en:"Gout", abbr:"", ja:"痛風", note:"尿酸結晶による関節炎。第1趾MTP関節が好発部位。", example:"The patient has acute gouty arthritis in the right big toe.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Tendinitis", abbr:"", ja:"腱炎", note:"腱の炎症。Achilles tendinitis / Patellar tendinitis など。", example:"Achilles tendinitis was diagnosed in the right ankle.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Bursitis", abbr:"", ja:"滑液包炎", note:"Prepatellar / Olecranon / Trochanteric bursitis など。", example:"Trochanteric bursitis was causing lateral hip pain.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Sprain", abbr:"", ja:"捻挫", note:"靭帯の部分・完全断裂。Grade 1〜3で重症度表現。", example:"He sustained a grade 2 ankle sprain during the game.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Strain", abbr:"", ja:"筋挫傷", note:"筋肉・腱の過伸展・断裂。Sprain（靭帯）と区別。", example:"A hamstring strain was confirmed by MRI.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Neurovascular status", abbr:"NV", ja:"神経血管状態", note:"Sensation / Motor / Pulse / CRT の確認。骨折・処置後に必須評価。", example:"Neurovascular status distal to the fracture was intact.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Deformity", abbr:"", ja:"変形", note:"Valgus（外反）/ Varus（内反）/ Angulation（屈曲変形）で表現。", example:"A valgus deformity of the right knee was noted.", cat:"symptom", level:"basic", dept:"ORTHO" },
{ en:"Swelling", abbr:"", ja:"腫脹", note:"外傷・炎症・感染による局所腫れ。Effusion（関節液貯留）と区別。", example:"Significant swelling was noted around the ankle joint.", cat:"symptom", level:"basic", dept:"ORTHO" },
{ en:"Joint effusion", abbr:"", ja:"関節液貯留", note:"外傷・炎症・感染で関節内に液体が貯留する。穿刺・超音波で確認。", example:"A large joint effusion was aspirated from the knee.", cat:"symptom", level:"intermediate", dept:"ORTHO" },
{ en:"Postoperative pain management", abbr:"", ja:"術後疼痛管理", note:"Multimodal analgesia（多剤併用鎮痛）が推奨。", example:"Postoperative pain was managed with scheduled acetaminophen and PRN opioids.", cat:"treatment", level:"intermediate", dept:"ORTHO" },
{ en:"Rehabilitation", abbr:"Rehab", ja:"リハビリテーション", note:"PT・OT・STが連携。早期離床・ADL訓練が重要。", example:"The patient was transferred to rehabilitation for intensive physical therapy.", cat:"treatment", level:"basic", dept:"ORTHO" },
{ en:"Lachman test", abbr:"", ja:"ラックマンテスト", note:"ACL損傷の評価。膝30°屈曲位で前方引き出し。感度最高。", example:"Lachman test was positive, suggesting an ACL injury.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"McMurray test", abbr:"", ja:"マクマレーテスト", note:"半月板損傷の評価。膝の回旋・屈曲伸展で疼痛・弾発音を確認。", example:"McMurray test was positive for medial meniscus tear.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Straight leg raise", abbr:"SLR", ja:"下肢伸展挙上テスト", note:"坐骨神経痛・腰椎椎間板ヘルニアの評価。陽性：30〜70°で放散痛。", example:"Straight leg raise was positive at 45 degrees on the right.", cat:"diagnosis", level:"basic", dept:"ORTHO" },
{ en:"Phalen's test", abbr:"", ja:"ファーレンテスト", note:"手根管症候群の評価。手首最大掌屈60秒で正中神経領域にしびれ。", example:"Phalen's test was positive, consistent with carpal tunnel syndrome.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Tinel's sign", abbr:"", ja:"チネル徴候", note:"神経圧迫部を叩打するとその神経支配領域にしびれが放散。", example:"Tinel's sign was positive over the carpal tunnel.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Drop arm test", abbr:"", ja:"ドロップアームテスト", note:"腱板断裂（特に棘上筋）の評価。腕を外転位から保持できない。", example:"Drop arm test was positive — a full-thickness rotator cuff tear was suspected.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Empty can test", abbr:"", ja:"エンプティカンテスト", note:"棘上筋腱の評価。缶を空にするような肢位で抵抗。", example:"The empty can test was positive for supraspinatus involvement.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Anterior drawer test", abbr:"", ja:"前方引き出しテスト", note:"ACLの評価。膝90°屈曲位で脛骨の前方移動を確認。", example:"Anterior drawer test was positive for ACL instability.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Valgus stress test", abbr:"", ja:"外反ストレステスト", note:"MCL（内側側副靭帯）の評価。外反方向に応力をかける。", example:"Valgus stress test was positive, indicating MCL injury.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },
{ en:"Varus stress test", abbr:"", ja:"内反ストレステスト", note:"LCL（外側側副靭帯）の評価。内反方向に応力をかける。", example:"Varus stress test was negative.", cat:"diagnosis", level:"intermediate", dept:"ORTHO" },

// ==================== 小児科 PED ====================
{ en:"Pediatric", abbr:"", ja:"小児の", note:"新生児(0-28d)・乳児(28d-1y)・幼児(1-3y)・学童(6-12y)・思春期(12-18y)。", example:"This is a 4-year-old pediatric patient with fever.", cat:"common", level:"basic", dept:"PED" },
{ en:"Febrile seizure", abbr:"", ja:"熱性痙攣", note:"6ヶ月〜5歳の発熱に伴う痙攣。単純型/複雑型に分類。", example:"The child had a febrile seizure with a temperature of 39.5°C.", cat:"diagnosis", level:"intermediate", dept:"PED" },
{ en:"Croup", abbr:"", ja:"クループ症候群", note:"吸気性喘鳴・犬吠様咳嗽・嗄声が三徴。Parainfluenzaが原因。", example:"The child presented with a barky cough and stridor — croup was diagnosed.", cat:"diagnosis", level:"intermediate", dept:"PED" },
{ en:"Otitis media", abbr:"AOM", ja:"中耳炎", note:"Acute Otitis Media。乳幼児の耳痛・発熱。鼓膜所見で診断。", example:"Otoscopy revealed a bulging erythematous tympanic membrane consistent with AOM.", cat:"diagnosis", level:"basic", dept:"PED" },
{ en:"Intussusception", abbr:"", ja:"腸重積", note:"腸管の陥入。間欠的腹痛・嘔吐・イチゴゼリー状血便が三徴。", example:"Ultrasound confirmed intussusception — barium enema reduction was attempted.", cat:"diagnosis", level:"intermediate", dept:"PED" },
{ en:"Growth chart", abbr:"", ja:"成長曲線", note:"身長・体重・頭囲を年齢別に評価。Percentileで表現。", example:"The child's weight is below the 3rd percentile on the growth chart.", cat:"diagnosis", level:"basic", dept:"PED" },
{ en:"Developmental milestone", abbr:"", ja:"発達マイルストーン", note:"運動・言語・社会性の発達指標。遅滞があれば評価を。", example:"The child is not meeting developmental milestones for speech.", cat:"diagnosis", level:"basic", dept:"PED" },
{ en:"Vaccination", abbr:"", ja:"予防接種", note:"Immunization とも。接種歴の確認が重要。", example:"Is the child up to date on all vaccinations?", cat:"common", level:"basic", dept:"PED" },

// ==================== 産婦人科 OB ====================
{ en:"Gravida / Para", abbr:"G/P", ja:"妊娠回数・分娩回数", note:"G3P2 = 妊娠3回・分娩2回。TPAL（Term・Preterm・Abortion・Living）とも。", example:"The patient is gravida 3, para 2.", cat:"common", level:"basic", dept:"OB" },
{ en:"Gestational age", abbr:"GA", ja:"妊娠週数", note:"最終月経（LMP）から計算。超音波での修正も行う。", example:"The gestational age is 32 weeks by LMP.", cat:"common", level:"basic", dept:"OB" },
{ en:"Prenatal care", abbr:"", ja:"妊婦健診", note:"定期的な母体・胎児評価。血圧・体重・尿検査・超音波を含む。", example:"The patient has had regular prenatal care throughout her pregnancy.", cat:"common", level:"basic", dept:"OB" },
{ en:"Preeclampsia", abbr:"", ja:"妊娠高血圧症候群", note:"BP ≥ 140/90 + 蛋白尿。Eclampsia（痙攣を伴う）と区別。", example:"Preeclampsia was diagnosed at 34 weeks gestation.", cat:"diagnosis", level:"intermediate", dept:"OB" },
{ en:"Cesarean section", abbr:"C/S", ja:"帝王切開", note:"Elective（予定）/ Emergency（緊急）に分類。", example:"An emergency cesarean section was performed for fetal distress.", cat:"treatment", level:"basic", dept:"OB" },
{ en:"Fetal heart rate", abbr:"FHR", ja:"胎児心拍数", note:"正常：110〜160 bpm。CTGモニタリングで評価。", example:"Fetal heart rate was 155 bpm with good variability.", cat:"vital", level:"basic", dept:"OB" },
{ en:"Contractions", abbr:"", ja:"陣痛（子宮収縮）", note:"頻度・強さ・持続時間を記録。Regular contractions = 規則的陣痛。", example:"She is having regular contractions every 3 minutes.", cat:"symptom", level:"basic", dept:"OB" },
{ en:"Ectopic pregnancy", abbr:"", ja:"子宮外妊娠", note:"卵管妊娠が最多。破裂すると出血性ショック。β-hCG + 超音波で診断。", example:"Ectopic pregnancy was suspected and confirmed by ultrasound.", cat:"diagnosis", level:"intermediate", dept:"OB" },

// ==================== 精神科 PSY ====================
{ en:"Depression", abbr:"MDD", ja:"うつ病", note:"Major Depressive Disorder。2週間以上の抑うつ気分・興味喪失など。", example:"The patient was diagnosed with major depressive disorder.", cat:"diagnosis", level:"basic", dept:"PSY" },
{ en:"Anxiety", abbr:"", ja:"不安障害", note:"GAD / Panic disorder / Social anxiety disorder に分類。", example:"The patient has generalized anxiety disorder with frequent panic attacks.", cat:"diagnosis", level:"basic", dept:"PSY" },
{ en:"Suicidal ideation", abbr:"SI", ja:"自殺念慮", note:"Active（計画あり）/ Passive（死にたい気持ち）を区別。安全評価が必須。", example:"The patient expressed suicidal ideation with a specific plan.", cat:"symptom", level:"intermediate", dept:"PSY" },
{ en:"Hallucination", abbr:"", ja:"幻覚", note:"Auditory（幻聴）/ Visual（幻視）/ Tactile（幻触）。統合失調症・せん妄で多い。", example:"The patient reports auditory hallucinations — hearing voices.", cat:"symptom", level:"intermediate", dept:"PSY" },
{ en:"Delusion", abbr:"", ja:"妄想", note:"訂正不能な誤った確信。Persecutory（被害妄想）/ Grandiose（誇大妄想）など。", example:"The patient has persecutory delusions and believes he is being followed.", cat:"symptom", level:"intermediate", dept:"PSY" },
{ en:"Delirium", abbr:"", ja:"せん妄", note:"急性の意識混濁・注意障害。入院高齢者に多い。Hyperactive / Hypoactive / Mixed。", example:"Post-operative delirium was managed with reorientation and low-dose haloperidol.", cat:"diagnosis", level:"intermediate", dept:"PSY" },
{ en:"Orientation", abbr:"", ja:"見当識", note:"Person（人物）/ Place（場所）/ Time（時間）の3方向で評価。", example:"The patient is oriented to person and place but not to time.", cat:"diagnosis", level:"basic", dept:"PSY" },

// ==================== 皮膚科 DERM ====================
{ en:"Rash", abbr:"", ja:"発疹", note:"Macular / Papular / Vesicular / Pustular / Urticarial で表現。", example:"A maculopapular rash was noted on the trunk and extremities.", cat:"symptom", level:"basic", dept:"DERM" },
{ en:"Urticaria", abbr:"", ja:"蕁麻疹", note:"Hives とも。アレルギー・感染・薬剤などが原因。", example:"The patient developed urticaria after taking penicillin.", cat:"diagnosis", level:"basic", dept:"DERM" },
{ en:"Cellulitis", abbr:"", ja:"蜂窩織炎", note:"皮膚・皮下組織の細菌感染。発赤・熱感・腫脹・疼痛が四徴。", example:"Cellulitis of the right lower leg was treated with antibiotics.", cat:"diagnosis", level:"basic", dept:"DERM" },
{ en:"Wound healing", abbr:"", ja:"創傷治癒", note:"Primary / Secondary / Tertiary intentionで分類。", example:"The wound is healing well by secondary intention.", cat:"treatment", level:"basic", dept:"DERM" },
{ en:"Pressure ulcer", abbr:"", ja:"褥瘡", note:"Decubitus ulcer とも。Stage 1〜4で重症度評価。", example:"A stage 3 pressure ulcer was found on the sacrum.", cat:"diagnosis", level:"intermediate", dept:"DERM" },

// ==================== 泌尿器科 URO ====================
{ en:"Dysuria", abbr:"", ja:"排尿痛", note:"排尿時の疼痛。UTI・尿道炎・前立腺炎で多い。", example:"The patient reports dysuria and frequency for 3 days.", cat:"symptom", level:"basic", dept:"URO" },
{ en:"Hematuria", abbr:"", ja:"血尿", note:"Gross（肉眼的）/ Microscopic（顕微鏡的）に分類。", example:"Gross hematuria prompted a CT of the urinary tract.", cat:"symptom", level:"basic", dept:"URO" },
{ en:"Urinary retention", abbr:"", ja:"尿閉", note:"排尿不能。BPH・神経因性膀胱が主な原因。カテーテル挿入で対処。", example:"The patient was unable to void — urinary retention was confirmed by bladder scan.", cat:"diagnosis", level:"basic", dept:"URO" },
{ en:"Benign prostatic hyperplasia", abbr:"BPH", ja:"前立腺肥大症", note:"高齢男性の下部尿路症状の主因。IPSS スコアで評価。", example:"BPH was managed with an alpha-blocker.", cat:"diagnosis", level:"basic", dept:"URO" },
{ en:"Kidney stones", abbr:"", ja:"尿路結石", note:"Renal calculi / Nephrolithiasis。側腹部の疝痛発作が特徴。", example:"CT showed a 6 mm kidney stone in the right ureter.", cat:"diagnosis", level:"basic", dept:"URO" },
{ en:"Foley catheter", abbr:"", ja:"尿道カテーテル（フォーリー）", note:"尿量管理・尿閉に使用。CAUTI（カテーテル関連尿路感染）に注意。", example:"A Foley catheter was inserted to monitor urine output.", cat:"treatment", level:"basic", dept:"URO" },

// ==================== 眼科 OPH ====================
{ en:"Visual acuity", abbr:"VA", ja:"視力", note:"Snellen chart で測定。20/20 が正常（米国）。", example:"Visual acuity is 20/200 in the right eye.", cat:"diagnosis", level:"basic", dept:"OPH" },
{ en:"Intraocular pressure", abbr:"IOP", ja:"眼圧", note:"正常：10〜21 mmHg。Glaucoma では上昇。", example:"IOP was elevated at 35 mmHg in the right eye.", cat:"diagnosis", level:"intermediate", dept:"OPH" },
{ en:"Glaucoma", abbr:"", ja:"緑内障", note:"視神経障害・視野欠損。IOPが危険因子。早期発見が重要。", example:"Open-angle glaucoma was diagnosed on routine examination.", cat:"diagnosis", level:"basic", dept:"OPH" },
{ en:"Cataract", abbr:"", ja:"白内障", note:"水晶体混濁。高齢者の視力低下の主因。手術で改善。", example:"A visually significant cataract was found in the left eye.", cat:"diagnosis", level:"basic", dept:"OPH" },
{ en:"Diplopia", abbr:"", ja:"複視", note:"Monocular / Binocular に分類。脳神経麻痺・眼筋麻痺で出現。", example:"The patient reports horizontal diplopia, worse on lateral gaze.", cat:"symptom", level:"intermediate", dept:"OPH" },

// ==================== 耳鼻咽喉科 ENT ====================
{ en:"Tinnitus", abbr:"", ja:"耳鳴り", note:"Subjective / Objective に分類。難聴・メニエール病・薬剤性など。", example:"The patient reports constant tinnitus in the right ear.", cat:"symptom", level:"basic", dept:"ENT" },
{ en:"Vertigo", abbr:"", ja:"回転性めまい", note:"BPPV / Meniere's disease / Vestibular neuritis など。", example:"BPPV was confirmed by the Dix-Hallpike test.", cat:"symptom", level:"basic", dept:"ENT" },
{ en:"Sore throat", abbr:"", ja:"咽頭痛", note:"Pharyngitis / Tonsillitis。Streptococcal pharyngitis はCentor基準で評価。", example:"The patient has a severe sore throat with exudative tonsillitis.", cat:"symptom", level:"basic", dept:"ENT" },
{ en:"Epistaxis", abbr:"", ja:"鼻出血", note:"Anterior（Kiesselbach部位・最多）/ Posterior に分類。", example:"Anterior epistaxis was controlled with direct pressure.", cat:"symptom", level:"basic", dept:"ENT" },
{ en:"Hearing loss", abbr:"", ja:"難聴", note:"Conductive（伝音性）/ Sensorineural（感音性）/ Mixed に分類。", example:"Pure tone audiometry confirmed sensorineural hearing loss.", cat:"symptom", level:"basic", dept:"ENT" },

// ==================== 放射線科 RAD ====================
{ en:"X-ray", abbr:"XR", ja:"X線撮影", note:"最も基本的な画像検査。骨折・肺炎・心拡大などを評価。", example:"An X-ray of the right wrist was ordered.", cat:"diagnosis", level:"basic", dept:"RAD" },
{ en:"CT scan", abbr:"CT", ja:"CT検査", note:"With contrast / Without contrast で指示。断面像が得られる。", example:"A contrast CT of the abdomen and pelvis was ordered.", cat:"diagnosis", level:"basic", dept:"RAD" },
{ en:"MRI", abbr:"MRI", ja:"MRI検査", note:"軟部組織・神経・脊椎の評価に優れる。金属制限に注意。", example:"MRI of the lumbar spine was ordered to evaluate for disc herniation.", cat:"diagnosis", level:"basic", dept:"RAD" },
{ en:"Ultrasound", abbr:"US", ja:"超音波検査", note:"放射線被曝なし。腹部・血管・妊婦に適している。", example:"Abdominal ultrasound showed gallstones without cholecystitis.", cat:"diagnosis", level:"basic", dept:"RAD" },
{ en:"Contrast", abbr:"", ja:"造影剤", note:"With contrast = 造影あり。腎機能・アレルギー歴を確認。", example:"Contrast was withheld due to the patient's elevated creatinine.", cat:"diagnosis", level:"intermediate", dept:"RAD" },
{ en:"Radiopaque", abbr:"", ja:"X線不透過性（白く写る）", note:"金属・骨・造影剤は白く写る。Radiolucent（黒く写る）の対語。", example:"A radiopaque foreign body was visible on the X-ray.", cat:"diagnosis", level:"intermediate", dept:"RAD" },
{ en:"Incidental finding", abbr:"", ja:"偶発所見", note:"主訴とは無関係に画像で発見された所見。フォローアップが必要なことも。", example:"An incidental pulmonary nodule was found on the CT scan.", cat:"diagnosis", level:"intermediate", dept:"RAD" },
{ en:"Report", abbr:"", ja:"読影レポート", note:"Impression（所見まとめ）/ Findings（詳細所見）の2部構成が多い。", example:"The radiology report showed no acute findings.", cat:"common", level:"basic", dept:"RAD" },

// ==================== 薬・処置 GEN ====================
{ en:"Analgesic", abbr:"", ja:"鎮痛薬", note:"NSAIDs / Acetaminophen / Opioid に分類。WHO 3段階除痛ラダー。", example:"An analgesic was prescribed for postoperative pain.", cat:"treatment", level:"basic", dept:"GEN" },
{ en:"Antibiotic", abbr:"Abx", ja:"抗菌薬", note:"培養結果が出たらde-escalationを検討。", example:"Empirical antibiotics were started pending culture results.", cat:"treatment", level:"basic", dept:"GEN" },
{ en:"Anticoagulant", abbr:"", ja:"抗凝固薬", note:"Heparin / Warfarin / DOAC（直接経口抗凝固薬）。出血リスクに注意。", example:"Anticoagulant therapy was initiated for the newly diagnosed DVT.", cat:"treatment", level:"intermediate", dept:"GEN" },
{ en:"Steroid", abbr:"", ja:"ステロイド", note:"Corticosteroid。抗炎症・免疫抑制作用。副作用管理が重要。", example:"A short course of oral steroids was prescribed for the allergic reaction.", cat:"treatment", level:"basic", dept:"GEN" },
{ en:"Diuretic", abbr:"", ja:"利尿薬", note:"Furosemide（ループ利尿薬）が代表。心不全・浮腫に使用。", example:"IV furosemide was given to treat the acute pulmonary edema.", cat:"treatment", level:"intermediate", dept:"GEN" },
{ en:"Vasopressor", abbr:"", ja:"昇圧薬", note:"Norepinephrine / Dopamine / Vasopressin など。MAP ≥ 65 mmHgを目標。", example:"Norepinephrine was started as a vasopressor for refractory hypotension.", cat:"treatment", level:"advanced", dept:"GEN" },
{ en:"Sedation", abbr:"", ja:"鎮静", note:"RASS スコアで鎮静深度を評価。Daily awakening trialが推奨。", example:"The patient required sedation for comfort during mechanical ventilation.", cat:"treatment", level:"intermediate", dept:"GEN" },
{ en:"Blood transfusion", abbr:"", ja:"輸血", note:"pRBC / FFP / PLT。Type & Screen → Crossmatchの手順。", example:"Two units of packed red blood cells were transfused.", cat:"treatment", level:"intermediate", dept:"GEN" },
{ en:"Central line", abbr:"CVC", ja:"中心静脈カテーテル", note:"Central Venous Catheter。CVP測定・輸液・TPN・昇圧薬投与に使用。", example:"A central line was placed in the right internal jugular vein.", cat:"treatment", level:"intermediate", dept:"GEN" },
{ en:"Arterial line", abbr:"A-line", ja:"動脈ライン", note:"持続的観血的血圧モニタリング。ABG採取にも使用。", example:"An arterial line was placed for continuous blood pressure monitoring.", cat:"treatment", level:"intermediate", dept:"GEN" },
{ en:"Nasogastric tube", abbr:"NGT", ja:"胃管", note:"胃内容除圧・経管栄養・薬剤投与に使用。", example:"A nasogastric tube was inserted for gastric decompression.", cat:"treatment", level:"basic", dept:"GEN" },
{ en:"Urinary catheter", abbr:"", ja:"尿道カテーテル", note:"尿量管理・尿閉に使用。CAUTI予防のため不要になったら早期抜去。", example:"A urinary catheter was inserted to monitor hourly urine output.", cat:"treatment", level:"basic", dept:"GEN" },
{ en:"Dose", abbr:"", ja:"用量", note:"投与量。mg / μg / units などで表現。", example:"The dose of metformin was increased to 1000 mg twice daily.", cat:"treatment", level:"basic", dept:"GEN" },
{ en:"Route of administration", abbr:"", ja:"投与経路", note:"PO（経口）/ IV（静注）/ IM（筋注）/ SC（皮下）/ SL（舌下）など。", example:"Antibiotics were changed from IV to PO as the patient improved.", cat:"treatment", level:"basic", dept:"GEN" },
{ en:"Half-life", abbr:"t½", ja:"半減期", note:"薬物濃度が半分になるまでの時間。投与間隔の決定に重要。", example:"The drug has a short half-life, so it needs to be given every 4 hours.", cat:"treatment", level:"intermediate", dept:"GEN" },
{ en:"Side effect", abbr:"", ja:"副作用", note:"Adverse drug reaction (ADR)。薬剤変更・投与中止の判断基準。", example:"The patient reported side effects of nausea and dizziness.", cat:"treatment", level:"basic", dept:"GEN" },
{ en:"Titrate", abbr:"", ja:"適正量に調整する", note:"Titrate to effect / to target BPなど。", example:"Titrate the vasopressor to maintain MAP above 65.", cat:"treatment", level:"intermediate", dept:"GEN" },
];
